### ISSUE TITLE
Writer planned?

### ISSUE THREAD

**Issue by matt2xu** [tafia/quick-xml#1]
Very promising crate, I like the emphasis on performance, and the simple API. I would gladly use it, except that my use case is to read XML, transform it (replace text, include other XML files, etc.), and then write the result.

Do you envision the crate to support writing XML as well? If so, this is something I would be glad to contribute! Hopefully with a quick writer, too :-)

**Comment by tafia** [comment]
I would welcome any contribution!
I haven't planned it in the short term because I don't need it yet. 
But I agree it could be very nice to have it.

**Comment by matt2xu** [comment]
Great! Just made a pull request for implementing the writer, see #2

**Comment by tafia** [comment]
That was fast!
Thanks for the PR, I'll review it asap
