### ISSUE TITLE
Corrupt symbols when reading 'ascii' encoding with non-ASCII escapes

### ISSUE THREAD

**Issue by idubrov** [tafia/quick-xml#106]
I'm not 100% sure, but I think unescape_and_decode does operations in wrong order.

I have an XML file which has 'ascii' encoding and uses escapes for non-ASCII characters. The current implementation will unescape character first (yielding UTF-8), then does "decode" (which, I think, corrupts this UTF-8 character, since document encoding is set to "ascii").

Link to the XML: http://unitsofmeasure.org/ucum-essence.xml

See the "ampere" definition at the line 252.

(obviously, the workaround for me is to change encoding from 'ascii' into 'UTF-8', as 'ascii' is a subset).

**Comment by tafia** [comment]
Thanks for the issue. I'll check on the spec.

**Comment by jonas-schievink** [comment]
XML in question:

    <name>amp&#232;re</name>

Generally, the encoding in the XML declaration is the encoding of the entire document, so `&xxx;` references are themselves encoded using that, and need to be decoded before they can even be detected, *then* replaced with the encoded code point.
