### ISSUE TITLE
panic when using clean buffers

### ISSUE THREAD

**Issue by phillord** [tafia/quick-xml#107]
I am getting a panic from the following code.

    extern crate quick_xml;

    use quick_xml::reader::Reader;
    use quick_xml::events::Event;

    pub fn main(){
        let ont_s = br#"<?xml version="1.0"?>
    <Ontology xmlns="http://www.w3.org/2002/07/owl#"
         xml:base="http://example.com/iri"
         xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:xml="http://www.w3.org/XML/1998/namespace"
         xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
         xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
         ontologyIRI="http://example.com/iri"
         versionIRI="http://example.com/viri">
      <Prefix name="o" IRI="http://example.com/iri#"/>
      <Prefix name="owl" IRI="http://www.w3.org/2002/07/owl#"/>
      <Prefix name="rdf" IRI="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
      <Prefix name="xml" IRI="http://www.w3.org/XML/1998/namespace"/>
      <Prefix name="xsd" IRI="http://www.w3.org/2001/XMLSchema#"/>
      <Prefix name="rdfs" IRI="http://www.w3.org/2000/01/rdf-schema#"/>
    </Ontology>
    "#;
    
        let mut reader = Reader::from_reader(&ont_s[..]);
        //let mut buf = vec![];
        //let mut ns_buf = vec![];

        loop{

            let mut buf = vec![];
            let mut ns_buf = vec![];
            match reader.read_namespaced_event(&mut buf, &mut ns_buf){
                Ok((_, Event::Eof)) => break,
                a=> {
                    println!("Event:{:?} {:?}", reader.buffer_position(), a);
                }
            }
        }
    }

    thread 'main' panicked at 'index 30 out of range for slice of length 0', /checkout/src/libcore/slice/mod.rs:745:4

If I comment out the declaration of `buf` and `ns_buf` inside the
loop, and just use a single pair defined outside instead, then,
magically it all works.

I should say, here, that I am new to rust, so it's possibly me being
daft. I don't really understand what I am supposed to be using these
two vectors for; however, to my mind, using a clean one for every
event should work, even if it is inefficient. Having it panic here,
but not with a shared buffer seems, to me, counter intuitive.

Thanks for the library!

**Comment by tafia** [comment]
This is expected behavior.

Let me explain:

The buffers are owning the data that is being parsed (there is intentionally no internal buffers). Thus the namespaces in particular are defined based on the `ns_buf` content (with positions etc). 

If you recreate them every time, then the namespace defined at the very beginning is just dropped. It may or may not be fine depending on your scenario:
- sometimes you want it to last for the whole document
- sometime you don't want to carry all that extra information while processing a sub node

I am sorry that the api is not more informative about such use cases.

**Comment by phillord** [comment]
Ah, okay, I didn't understand that from the documentation.

Unfortunately, I wanted to pass both the reader and the buffers to another function inside my `match` statement, so I could build a recursive parser. But this fails because, as far as I can see, the Event object borrows the buffers, so that I cannot pass them mutable to another function.

Well, I shall think on it. Thanks for the feedback.
