### ISSUE TITLE
Absence of git tags

### ISSUE THREAD

**Issue by phillord** [tafia/quick-xml#108]
Would it be possible to get tags onto release commits

**Comment by jonas-schievink** [comment]
I've used [cargo-release](https://github.com/sunng87/cargo-release) to automate this with great success!

**Comment by phillord** [comment]
https://github.com/tafia/quick-xml/tags

Not as far as I can see. Did you push them? Git makes you do this explicitly, for some obscure reason

**Comment by jonas-schievink** [comment]
Ah, no, I didn't mean with this project, but with my own. @tafia will have to do it here.

**Comment by phillord** [comment]
@jonas-schievink Oh, sorry, my confusion!

**Comment by tafia** [comment]
I pushed all tags starting version 0.4.2.
Thanks for opening the issue!

**Comment by phillord** [comment]
All looks good. Many thanks!
