### ISSUE TITLE
BytesStart unescaped method returns the attributes in the same result

### ISSUE THREAD

**Issue by MarkDDR** [tafia/quick-xml#118]
If you had for example the following xml snippet `<namespace:hello&gt; greeting='wave'>` and the corresponding BytesStart for that, (let's called the `element`), `element.unescaped()` would return `namespace:hello> greeting='wave'`, while `.name()` and `local_name()` only include the actual tag part (`namespace:hello&gt;` and `hello&gt;` respectively), and not the attributes.

This goes against the documentation which says it should just return the unescaped tag name.

**Comment by e00E** [comment]
This is still broken:

```rust
#[test]
fn test() {
    let xml = "<name attribute=\"value\">";
    let mut reader = quick_xml::Reader::from_str(xml);
    reader.trim_text(true);
    let mut buf = Vec::new();
    let start_event = match reader.read_event(&mut buf).unwrap() {
        Event::Start(e) => e,
        _ => unreachable!(),
    };

    let raw_name_bytes = start_event.name();
    let raw_name = std::str::from_utf8(raw_name_bytes).unwrap();
    // ok
    assert_eq!(raw_name, "name");

    let name_bytes = start_event.unescaped().unwrap();
    let name = std::str::from_utf8(name_bytes.as_ref()).unwrap();
    // fails
    assert_eq!(name, "name");
}
```
