### ISSUE TITLE
BytesStart .with_attributes() and .extend_attributes() seem redundant

### ISSUE THREAD

**Issue by mark-blum** [tafia/quick-xml#120]
Both of these methods do the same thing, in fact `.with_attributes()` calls `.extend_attributes()` do perform its function. The only real difference is that `.with_attributes()` consumes `self` while `.extend_attributes()` uses `&mut self`. Since there's no real value in having both of these in my opinion, I propose we remove `.with_attribtues()` and instead only use `.extend_attributes()`.

**Comment by mark-blum** [comment]
After further consideration, it occurs to me that `.with_attributes()` is meant to be used with `.owned()` or `.borrowed()` constructor to make some 1 liners. I still think having both is redundant but at least I see the reason for it.

**Comment by tafia** [comment]
I agree it is redundant but it is not too bad as they have slightly different purpose. I am not sure it is important enough to make a breaking change.

Closing for now, fell free to reopen if you want to discuss it further.
