### ISSUE TITLE
Doctypes and entities

### ISSUE THREAD

**Issue by jrozner** [tafia/quick-xml#124]
I'm working on parsing XML files that may utilize external entities. Currently when I throw them through quick-xml parsing the doctype is totally fine but when it gets to the entity there is an error because it's not an entity that is explicitly in the code. I definitely don't want the external entities to be able to bring in files or execute anything but do you have an opinion on allowing them to register new entities so that parsing will at least succeed? The replacement would essentially not be done but it would be able to check for the presence of a document defined entity.

**Comment by jechase** [comment]
Hey, any updates on this?

**Comment by Mingun** [comment]
After merging #261 it is possible to use custom entities
