### ISSUE TITLE
Support single quote in attributes

### ISSUE THREAD

**Issue by hkcorac** [tafia/quick-xml#126]
Hello,

May I ask if you could consider adding support for single quote in attributes?

For example current version `0.12.1` produces:

```xml
<tag key="value"></tag>
```

I wish there could be an option to choose between double quote and single quote, so this could be doable:

```xml
<tag key='value'></tag>
```

My most concern is some existing projects use double quote, some use single quote. If the crate can support both of them, it could help prevent noises in git...

Thank you,

**Comment by tafia** [comment]
Quick-xml already supports both when reading. I see no reason not to
support it for writing as well. If you want to give it a try I'd be happy
to merge it!

**Comment by hkcorac** [comment]
@tafia,

Hi, I'm sorry I got lost  :-D  Just find some time now.

Would you agree if I make a `Formatter` struct, which holds common settings (single quote, double quote, indent...)? The idea is inspired by `serde_json`'s [formatters](https://docs.serde.rs/serde_json/ser/index.html).

**Comment by hkcorac** [comment]
I'm sorry, I have very limited time to contribute. So I'm closing the issue. Hopefully someone else will have time to implement the feature.

**Comment by tafia** [comment]
No worries. Thank you anyway!
