### ISSUE TITLE
Getting to deeply nested XML

### ISSUE THREAD

**Issue by jamessewell** [tafia/quick-xml#127]
Hi,

Is there an easy way of wading through deeply nested XML?

For example, to get to:
```
{configData.xsd}configData/{genericNrm.xsd}SubNetwork/{genericNrm.xsd}SubNetwork/{genericNrm.xsd}MeContext/{genericNrm.xsd}ManagedElement/{utranNrm.xsd}RncFunction/{utranNrm.xsd}at
    tributes/{utranNrm.xsd}mcc")
```
Would I need a nested loop+match for each level?

Or is there a way of finding out the parents of a StartEvent?

Cheers,
James

**Comment by tafia** [comment]
You have to handle it yourself yes.

I usually use enums to manage states and match on `(event, state)` directly instead of nested loops.

I wanted to write a macro/function for that but finding the right balance is hard and it is not 'too' hard to do it yourself.

**Comment by jamessewell** [comment]
I might be missing something, but wouldn't an enum make it hard to target

`{schema1}:tag1/{schema1}:tag2`

but not

`{schema1}:tag1/{schema1}:tag3/{schema1}:tag2`

I've been having a play with a macro - but you are right it's really hard to get a balance of usability and concise macro syntax.

**Comment by tafia** [comment]
The enum is just here to represent the state machine. You can do whatever you want with it including saving some intermediary values:

Below is a basic example (not tested but you should get it). You cannot get to tag3 without getting to tag1/tag2 first.


```rust
struct Extract {
   key: String,
   values: Vec<String>,
}

enum State {
    Root,
    Tag1,
    Tag2 { extract: Extract },
}

/// Searches for tag1/tag2/tag3, returns all [tag2[@my_att], [tag3.text]]
fn extract<R: ...>(reader: &mut Reader<R>) -> Result<Vec<Extract>> {
    let mut buf = Vec::with_capacity(200);
    let mut txt = Vec::with_capacity(100);
    let mut state = State::Start;
    let mut res = Vec::new();
    loop {
        match (state, reader.read_event(&mut buf)?) {
            (State::Root, Event::Start(ref e)) if e.name() == b"tag1" => state = State::Tag1,
            (State::Tag1, Event::Start(ref e)) if e.name() == b"tag2" => {
                let my_att = e.attributes()
                              .filter_map(|a| a.ok())
                              .find(|a| a.key == b"my_att")
                              .ok_or(MyError::MyAttNotFound)?
                              .unescape_and_decode_value(&reader)?;
                let extract = Extract { key: my_att, values: vec::new() };
                state = State::Tag2 { extract: extract };
            }
            (State::Tag2 { ref mut extract }, Event::Start(ref e)) if e.name() == b"tag3" => {
                extract.values.push(reader.read_text(b"tag3", &mut txt)?);
                txt.clear();
            }

            (State::Tag2 { extract }, Event::End(ref e)) if e.name() == b"tag2" => {
                res.push(extract);
                state = State::Tag1;
            }
            (State::Tag1, Event::End(ref e)) if e.name() == b"tag1" => state = State::Root,
            _ => (), // else, do nothing, perhaps you should check it and make sure everything is fine
        }
        buf.clear();
    }

    match state {
        State::Root => Ok(res),
        s => Err(Error::UnexpectedState(s)),
    }
}
```

**Comment by jamessewell** [comment]
Hey,

OK that makes sense.

The use case I'm looking at is a streamer extracting information and making
changes in-line.

It's targeting three areas in the XML file, some of which are pretty deep.
That makes the state thing feel quite awkward, and it would make code which
was pretty hard to read.

Anyway I'm sure I'll get there - I could probably use something higher
level, but I want the speed!

Cheers,

**Comment by tafia** [comment]
As long as you can find some deep invariant it shouldn't be too complicated I think.
Hope you'll manage to make it! Ask if you have any doubt.

I agree this is definitely much harder to read than a XPath but I think it is still ok.

I'm curious to know if you manage to do it and to get the max performance :rocket: !

Closing for the moment, feel free to reopen.

**Comment by jamessewell** [comment]
Hi,

Yeah all good to close.

I ended up implementing a `Parents `struct which contains a `Vec<Tag>`. `Tag` is just the binary namespace and tag names.

Then I use a state `enum `like above to enable / disable parent tracking. When it's enabled I `push `each namespace/tag onto `Parents` at :::Start and `pop` it off at ::End.

That way when I'm in a deeply nested area I can just compare a String like `"{ns}tag/{ns}tag/{ns}tag"` to Parent to get what I want. 

I lose *some* performance, but for my use case it's not too bad.

Thanks for the help!

**Comment by tafia** [comment]
Ok I see.

Fyi, I have created long ago this [nested](https://crates.io/crates/nested) crate which can probably be faster (less allocation) in your case I guess.
