### ISSUE TITLE
EscapeError(UnterminatedEntity) when doing unescape_and_decode on a CDATA containing an ampersand

### ISSUE THREAD

**Issue by bbigras** [tafia/quick-xml#129]
I'm trying to use `unescape_and_decode()` on a CDATA similar to the following. I don't even know if the source XML is valid or if the ampersand should be encoded.

```xml
<tag><![CDATA[some & thing]]></tag>
```

error
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EscapeError(UnterminatedEntity(14..39))', libcore/result.rs:945:5
```

**Comment by tafia** [comment]
Sorry for the late response.
As [per the spec](https://www.w3.org/TR/REC-xml/#sec-cdata-sect) the content of CData is not supposed to be escaped, so you shouldn't use that function.

**Comment by bbigras** [comment]
No worries. Thank you very much.
