### ISSUE TITLE
quick_xml reader is private

### ISSUE THREAD

**Issue by icommit** [tafia/quick-xml#131]
**_use quick_xml::reader::Reader;_**

**error[E0603]: module `reader` is private**

**Comment by tafia** [comment]
reader and writer modules are now reexported from the root of the crate.
```rs
use quick_xml::Reader;
```

**Comment by Vagrantin** [comment]
Hello @tafia,
First of all thanks for the great tool !

Maybe it would be good to update the doc ?
https://crates.io/crates/quick-xml

my2cents

![Image](https://github.com/user-attachments/assets/a9177255-becb-4a81-89db-8d2cd51a1634)

**Comment by Mingun** [comment]
`reader` module was made public since creating this issue.
