### ISSUE TITLE
Debug representation is not always helpful

### ISSUE THREAD

**Issue by phillord** [tafia/quick-xml#138]
I am trying to debug my own code for which I use the standard "println! everything" approach. Under these circumstances, the debug format of the various `Event` structs is not that helpful. I get lots of things like: 

    About to read tag: ([], Text(BytesText { content: [10, 32, 32, 32, 32, 32, 32, 32, 32] }))
    About to read tag: ([104, 116, 116, 112, 58, 47, 47, 119, 119, 119, 46, 119, 51, 46, 111, 114, 103, 47, 50, 48, 48, 50, 47, 48, 55, 47, 111, 119, 108, 35], Empty(BytesStart { buf: [67, 108, 97, 115, 115, 32, 73, 82, 73, 61, 34, 35, 66, 34], name_len: 5 }))

It would be really nice if the internal buffers were decoded when printing out. Of course, I can add this functionality myself, but I am guessing most users of the library would want to see text and not numbers.

**Comment by phillord** [comment]
Yeah, I realised that. It's very easy to do this if you assume that you have utf8, otherwise you need the reader to decode. In a sense, the simple short term solution would be just to ignore the problem of non-utf-8 -- I mean, it's not going to be harder to read than currently.

**Comment by Mingun** [comment]
It seems that this issue already fixed and can be closed.
