### ISSUE TITLE
feature request: getting the reference of the inner wirter without consuming it

### ISSUE THREAD

**Issue by PoiScript** [tafia/quick-xml#141]
I'm writing a library for generating office docx files right now. As you can see, docx is just a batch of xml files in a zip archive. So I'm actually putting a `ZipWriter` into the quick-xml's `Writer`.

But every time I finished writing a xml file and attempted to write the next one, I had to cosume it to get the inner `ZipWriter`, call some functions on the `ZipWriter`, and build another `Writer` again.

So it would be great to get the reference of the inner wirter without consuming it, by providing a method or even making it publish.

**Comment by tafia** [comment]
I am clearly not against providing a way to get a reference to the writer.
In the meantime, can you work around your issue by initializing the writer with `&mut writer` instead of `writer`? (because of `impl<'a, W: Write + ?Sized> Write for &'a mut W`)

**Comment by dralley** [comment]
Isn't this covered now by `inner()`?  https://docs.rs/quick-xml/0.22.0/quick_xml/struct.Writer.html#method.inner
