### ISSUE TITLE
Xml declaration error

### ISSUE THREAD

**Issue by PhnxRbrn** [tafia/quick-xml#15]
I am now getting a thread '<main>' panicked at 'Malformed("Xml declaration must start with \'?xml \'") at position 130', but the xml does start with <?xml.

**Comment by tafia** [comment]
Sorry!
Can you provide an XML to test ?

**Comment by PhnxRbrn** [comment]
https://github.com/red-oxide/feed/blob/master/rsc/sample_rss.xml

**Comment by tafia** [comment]
There is a [Processing Instruction](https://www.w3.org/TR/2008/REC-xml-20081126/#NT-PITarget) `xml-stylesheet` not managed.
I've added a new `Event::PI` for this.
Do you allow me to use that sample file in my examples to ensure non-regression?

**Comment by PhnxRbrn** [comment]
Sure go ahead

**Comment by tafia** [comment]
I close it, feel free to reopen it if it still doesn't work!
Thanks again for the issue and sorry about that.

Publishing v0.1.7 to crates.io
