### ISSUE TITLE
Using with NamedTempFile?

### ISSUE THREAD

**Issue by Dentrax** [tafia/quick-xml#155]
I'm having some problems when i am using [NamedTempFile](https://stebalien.github.io/tempfile/tempfile/struct.NamedTempFile.html) with `quick-xml`.

I was using that way with `xml-rs`.

```
let file = NamedTempFile::new().expect("Could not create tempfile");
let path = file.path().to_str().expect("Could not find tempfile").to_string();

let buf_reader = BufReader::new(file.as_file());
let xml_reader = EventReader::new(buf_reader);
```

So, I couldn't figure it out how to use _NamedTempFile_ with _quick-xml_. 

There is no `new` function like [xml-rs](http://netvl.github.io/xml-rs/xml/reader/struct.EventReader.html) that takes parameters with the `BufReader`. What should I do in this case?

P.S: I'm new in **Rust**! Thank you! @tafia

**Comment by tafia** [comment]
You can use the [`from_reader`](https://docs.rs/quick-xml/0.14.0/quick_xml/struct.Reader.html#method.from_reader) instead of the new.

Welcome to rust!

**Comment by Dentrax** [comment]
Thank you!!!
