### ISSUE TITLE
xml-rs equivalents for getting attributes as string

### ISSUE THREAD

**Issue by Dentrax** [tafia/quick-xml#156]
Hey,

After reading a few hours of `quick-xml` documents, and examples, I still couldn't do what I wanted. I am new at Rust, I might be missing something.

```
        let buf_reader = BufReader::new(file.as_file());
        let xml_reader = EventReader::new(buf_reader);

        for entry in xml_reader {
            match entry {
                Ok(XmlEvent::StartElement {
                    name, attributes, ..
                }) => {
                    if name.local_name.eq("tag1") {
                        current = Some(Test::new());
                        
                    }
                    let test = match &mut current {
                        Some(x) => x,
                        None => continue,
                    };
                    if name.local_name.eq("tag1") {
                        for attr in &attributes {
                            if attr.name.local_name.eq("attr_key") && attr.value.eq("attr_value") {
                                //...
                            }
                        }
                    }  
.........
```

1. What is the equivalent of this `xml-rs` code for `quick-xml`?
2. I am using this: `let f = String::from_utf8(e.name().to_vec()).unwrap();` to get names as string. Is that correct way?
3. I don't know why this is not working: `no field key on type ...`

```
for attr in e.attributes() {
    if attr.key == b"test" {
     // ...
    }
 }
```

Suggestion: Having more examples could be definitely be better btw. :)

Thank you!

**Comment by tafia** [comment]
I forgot about your issue sorry!
I know it's been 20 days already but in case.

quick-xml tries to make use go deeper level without sacrificing to much convenience. So in general instead of matching `str`ings (utf8 only for xmlrs) you can directly match `&[u8]`.

checking event names:
```rust
name.local_name.eq("tag1") => event.name() == b"tag1"
```

checking attribute names:
```rust
if attr.name.local_name.eq("attr_key") && attr.value.eq("attr_value")

=>

if attr.key == b"attr_key" && &*attr.value == b"attr_value"
```

The purpose is
- to allow comparing non utf8 is needed
- to avoid converting to utf8 when we can
