### ISSUE TITLE
XML canonicalization and signatures (c14n, etc.)

### ISSUE THREAD

**Issue by burdges** [tafia/quick-xml#163]
Is there any interest in XML canonicalization and signatures?  Or would these things be beyond the scope/interests of the project?

https://en.wikipedia.org/wiki/XML_Signature
https://www.w3.org/TR/xml-c14n/ (c14n)
https://www.w3.org/TR/xml-exc-c14n/ (c14n-exc)
https://www.w3.org/TR/xmldsig-core/ (dsig) 

Related:  https://github.com/netvl/xml-rs/issues/161

**Comment by tafia** [comment]
Thanks for opening the issue. In my point of view, this is a higher level operation that should probably be done out of this library. In am not familiar with XML signatures but from the wikipedia page, it involves XPath in particular which is not implemented here.
It may make more sense in a higher level library such as [minidom](https://crates.io/crates/minidom) ?

**Comment by burdges** [comment]
At first blush minidom sounds too high level but sure outside this crate makes sense.
