### ISSUE TITLE
Confusion about read_event and buffer usage

### ISSUE THREAD

**Issue by desbma** [tafia/quick-xml#164]
First thanks for making this library, I have converted some code from xml-rs, and got a x15 speedup with very little changes in my code.

From the [documentation of read_event](https://docs.rs/quick-xml/0.15.0/quick_xml/struct.Reader.html#method.read_event):

> Having the possibility to control the internal buffers gives you some additional benefits such as:
> Reduce the number of allocations by reusing the same buffer. For constrained systems, you can call buf.clear() once you are done with processing the event (typically at the end of your loop).

However `buf.clear()` does not free memory, it only changes the vector size:

> Clears the vector, removing all values.
> 
> Note that this method has no effect on the allocated capacity of the vector.

https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html#method.clear

Or am I missing something?
(I am a Rust beginner)

**Comment by tafia** [comment]
> I have converted some code from xml-rs, and got a x15 speedup with very little changes in my code.

Awesome! Congrats

> However buf.clear() does not free memory, it only changes the vector size:

You are right that not space if freed, but it can be reused with no extra allocation in a loop.

To free that space you would probably need to [shrink it](https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html#method.shrink_to_fit).

Documentation is hard...

**Comment by desbma** [comment]
OK, I get it now, what I missed is that each `read_event` call appends to the end of the vector, and does not overwrite it from the start.
In that case, calling `buf.clear()` after each call makes sense.

**Comment by tafia** [comment]
Yes sorry I thought that was clear (using a `Vec` instead of a `&[..]`)

**Comment by desbma** [comment]
I'm still learning Rust, so I don't know the expected conventions...

I'm closing this then.
