### ISSUE TITLE
When publish version 0.17.1 on crates.io

### ISSUE THREAD

**Issue by andreevlex** [tafia/quick-xml#174]
Hello.
I like the new feature to support serde.
Tell me when you plan to publish version 0.17.1 on crates.io?
Thank you.

**Comment by tafia** [comment]
Hey!
I want to polish a little more, for instance I want at the very least to pass all serde-xml-rs tests (not the case at the moment, looking at it).
I hope to be done by the end of the week.

**Comment by tafia** [comment]
Published!
