### ISSUE TITLE
Deserialization Behavior on Unit Struct

### ISSUE THREAD

**Issue by davidbarsky** [tafia/quick-xml#175]
First of all, congrats on getting the 0.17.1 out with support for serde! I was going to write my own, but I'm glad you there first :). 

Second, I'm trying out this library for (de)serializing data from S3, but I've noticed that S3 tends to have some _odd_ representations of XML response.  For instance, this is the representation of the response to [the `GetBucketTagging` API call](https://docs.aws.amazon.com/en_pv/AmazonS3/latest/API/API_GetBucketTagging.html):

```xml
<GetBucketTaggingOutput>
   <TagSet>
      <Tag>
         <Key>string</Key>
         <Value>string</Value>
      </Tag>
   </TagSet>
</GetBucketTaggingOutput>
```

I wrote the following Rust code to _serialize_ to XML:

```rust
#[derive(Serialize, Deserialize, Debug, PartialEq)]
struct GetBucketTaggingOutput {
    #[serde(rename = "TagSet")]
    pub tag_set: Vec<Tag>,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Tag {
    /// Name of the tag.
    #[serde(rename = "Key")]
    pub key: String,
    /// Value of the tag.
    #[serde(rename = "Value")]
    pub value: String,
}
```

With the sequence changes I made [in my fork](https://github.com/davidbarsky/quick-xml/), this is able to serialize correctly to:

```xml
<GetBucketTaggingOutput>
    <TagSet>
        <Tag>
             <Key>string</Key>
             <Value>string</Value>
        </Tag>
    </TagSet>
</GetBucketTaggingOutput>
```

However, _deserialization_ fails with the following error:

```
thread 'test_read_tagging' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("missing field `Key`")', src/libcore/result.rs:1165:5.
```

How _should_ this data be represented in Rust, and if it's not representable in Rust with quick-xml, I'd be happy to send a PR that _does_ make it representable!

**Comment by tafia** [comment]
Thanks for trying it out!

First I'd be happy to add the sequence, would you mind opening a PR?

For the deserialization issue, I made it work using an intermediary `TagSet` struct:

```rust
#[test]
fn get_bucket_tagging() {
    let src = " 
<GetBucketTaggingOutput>
   <TagSet>
      <Tag>
         <Key>string</Key>
         <Value>string</Value>
      </Tag>
   </TagSet>
</GetBucketTaggingOutput>";

    #[derive(Serialize, Deserialize, Debug, PartialEq)]
    struct GetBucketTaggingOutput {
        #[serde(rename = "TagSet")]
        tag_set: TagSet,
    }   

    #[derive(Serialize, Deserialize, Debug, PartialEq)]
    struct TagSet {
        #[serde(rename = "Tag")]
        tags: Vec<Tag>,
    }   

    #[derive(Serialize, Deserialize, Debug, PartialEq)]
    struct Tag {
        /// Name of the tag.
        #[serde(rename = "Key")]
        key: String,
        /// Value of the tag.
        #[serde(rename = "Value")]
        value: String,
    }   

    let bucket_tagging: GetBucketTaggingOutput = from_str(src).unwrap();

    assert_eq!(bucket_tagging, GetBucketTaggingOutput {
        tag_set: TagSet {
            tags: vec![Tag {
                key: "string".to_string(),
                value: "string".to_string(),
            }],
        }
    }); 
}
```

**Comment by davidbarsky** [comment]
Thanks for your help! I was able to get this working here: https://github.com/davidbarsky/quick-xml/commit/f4b2b2e7246306428dc1e6727fb24fe3262f7743. It's a bit late for me now, do you mind if I send you that PR for `seq` (my location; UTC-5) tomorrow morning?

**Comment by davidbarsky** [comment]
(I was able to get this working _with your help_, I should clarify!)

**Comment by messense** [comment]
@davidbarsky Shameless plug, you can get rid of the intermediary `TagSet` struct with [serde-single-key-map](https://crates.io/crates/serde-single-key-map)
