### ISSUE TITLE
Deserialization behavior for Vec

### ISSUE THREAD

**Issue by agodnic** [tafia/quick-xml#177]
Hi!

I've noticed that the library fails to deserialize fields of type `Vec<_>` if the vec elements are not adjacent.
I'm not sure if this is the intended behavior or not, but [files like this do appear in the wild](https://github.com/quickfix/quickfix/blob/3e87689b89764fa2555b990d9fd5ed7914ce451a/spec/FIX50.xml#L5).

# Cargo.toml
```
[package]
name = "minimal"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
serde = { version = "1.0", features = [ "derive" ] } 
quick-xml = { version = "0.17.1", features = ["serialize"] }
```

# src/lib.rs
```
#[derive(serde::Deserialize)]
struct Xml {
    field1: Vec<Field1>,
    field2: Vec<Field2>,
}

#[derive(serde::Deserialize)]
struct Field1 {
    name: String,
}

#[derive(serde::Deserialize)]
struct Field2 {
    name: String,
}

#[test]
fn it_works() {

    let s = r#" 
<Xml>
    <field1 name='a'/>
    <field2 name='b'/>
    <field1 name='a'/>
</Xml>
"#;

    let xml: Xml = ::quick_xml::de::from_str(s).unwrap();
}
```

# Error
```'called `Result::unwrap()` on an `Err` value: Custom("duplicate field `field1`")',```

**Comment by tafia** [comment]
I believe this is an issue with serde itself. I am not sure though.
One way to fix it might be to use enums:
```rust
#[test]
fn no_contiguous_fields(){

    #[derive(Deserialize, PartialEq, Debug)]
    struct Xml {
        #[serde(rename= "$value")]
        fields: Vec<Field>,
    }   

    #[derive(Deserialize, PartialEq, Debug)]
    enum Field {
        #[serde(rename = "field1")]
        Field1 { name: String },
        #[serde(rename = "field2")]
        Field2 { name: String },
    }   

    let s = r#" 
<Xml>
    <field1 name='a'/>
    <field2 name='b'/>
    <field1 name='a'/>
</Xml>
"#;

    let xml: Xml = ::quick_xml::de::from_str(s).unwrap();
    assert_eq!(xml, Xml {
        fields: vec![
            Field::Field1 { name: "a".to_string() },
            Field::Field2 { name: "b".to_string() },
            Field::Field1 { name: "a".to_string() },
        ],
    }); 
}
```

**Comment by agodnic** [comment]
The enum version works for me. Thanks!

**Comment by polarathene** [comment]
@tafia this workaround you're suggesting requires all possible fields that will appear to be wrapped into an enum? 

I have run into this error(info shared on https://github.com/serde-rs/serde/issues/1725), but in my case my "duplicate" field is only duplicate by name, not values. As soon as any different field is mixed inbetween the field to be collected into a `Vec`, even if that unrelated field is not defined in the struct, it will trigger this duplicate field error.

Seems that it collects the elements in sequence, then breaks once a different element/field appears, instead of continuing to check for more of that field in the siblings by completing the iteration.

---

I suppose an alternative workaround if this is an issue is to collect all children fields via single field and the [serde `flatten` attribute](https://serde.rs/attr-flatten.html#capture-additional-fields)? Then filter/process manually?

**EDIT:** In my case this works well and can still allow for multiple fields, but I have a deserializer for each field with multiple elements to collect into. Here's what I've done if it's helpful to anyone to reference(see linked issue for example XML and some extra info):

```rust
#[derive(Debug, Deserialize, PartialEq, Default)]
struct Material {
    name: String,
    unique: Option<bool>, //TODO: in xml when false, value is not included?
    render_template: String,
    version: u8,

    #[serde(flatten, deserialize_with = "de_texture")]
    textures: HashMap<String, Texture>,

    #[serde(flatten, deserialize_with = "de_variable", default)]
    variables: VarHash,
}


#[derive(Debug, Deserialize, PartialEq)]
struct Texture {
    file: Option<String>,
    #[serde(rename = "type", default)]
    format: Option<String>,
    global_texture: Option<String>,
}


// Given the child elements of `material`, filter to elements with `_texture` suffix
// and return them collected in a `HashMap::<String, Texture>`
fn de_texture<'de, D>(deserializer: D) -> Result<HashMap<String, Texture>, D::Error>
where
    D: Deserializer<'de>,
{
    struct ChildVisitor;
    impl<'de> Visitor<'de> for ChildVisitor
    {
        type Value = HashMap<String, Texture>;

        fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
            formatter.write_str("Map of children elements - filtering for fields with `_texture` suffix")
        }

        fn visit_map<M>(self, mut access: M) -> Result<Self::Value, M::Error>
        where
            M: MapAccess<'de>,
        {
            let mut texture_hm = HashMap::<String, Texture>::new();

            while let Some(key) = access.next_key::<String>()? {
                if key.ends_with("_texture") {
                    let truncate_suffix = key.len() - "_texture".len();
                    let mut truncated_key = key[..truncate_suffix].to_string();

                    if truncated_key == "bump_normal" {
                        truncated_key = "normal".to_string();
                    }

                    let texture = access.next_value::<Texture>().unwrap();
                    texture_hm.insert(truncated_key, texture);
                }
            };

            Ok(texture_hm)
        }
    }

    deserializer.deserialize_any(ChildVisitor{})
}

// Given the child elements of `material`, filter to elements with `variable` field
// and collect into `Vec<Variable>`, where the `VarHash::From` impl method will convert
// to desired `VarHash` type(HashMap<String, Vars>`. 
// Required to avoid error when children of this field are non-contiguous(other field types
// interrupt the sequence)
fn de_variable<'de, D>(deserializer: D) -> Result<VarHash, D::Error>
where
    D: Deserializer<'de>,
{
    struct ChildVisitor;
    impl<'de> Visitor<'de> for ChildVisitor
    {
        type Value = VarHash;

        fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
            formatter.write_str("Map of children elements - filtering for field: `variable`")
        }

        fn visit_map<M>(self, mut access: M) -> Result<Self::Value, M::Error>
        where
            M: MapAccess<'de>,
        {
            let mut variables = Vec::<Variable>::new();

            while let Some(key) = access.next_key::<String>()? {
                if key == "variable" {
                    let var = access.next_value::<Variable>().unwrap();
                    variables.push(var);
                }
            };

            Ok(VarHash::from(variables))
        }
    }

    deserializer.deserialize_any(ChildVisitor{})
}
```

**Comment by tafia** [comment]
Awesome, thanks for the comment!
Not sure where to put this kind of information for people who're having the same issue.

**Comment by polarathene** [comment]
@tafia You could just include a troubleshooting section in the README + docs.rs?

Link to issues like this one. Makes the issues more discoverable, so the problem can be understood and workarounds used, along with any further discussion if something better comes along(like a fix in serde).

This issue could be linked as "Siblings with the same tag name will only deserialize into a Vec correctly when their sequence order is a single contiguous slice (See workarounds here)", or something along those lines?

Or you could create a separate MD doc with the problem example data shown, and each workaround. That saves the user from reading through longer discussion threads, which can be linked to as well if they have anything to add, or want to watch the issue for updates.

**Comment by tobz1000** [comment]
I currently have a [PR](https://github.com/RReverser/serde-xml-rs/pull/143) up for the equivalent [issue](https://github.com/RReverser/serde-xml-rs/issues/55) in the `serde-xml-rs` crate. I think it would be fairly straightforward to port to this crate too. I plan to have a PR ready at some point if it would be welcomed.

**Comment by tobz1000** [comment]
I have a mostly complete branch at: https://github.com/tobz1000/quick-xml/tree/out-of-order-elements

The architectural changes could be improved, and there is a failing unit test which I need to track down. However, before I go further, it would be good to understand the status of #208, since it's modifying some of the same code.

**Comment by lwilli** [comment]
Thanks @tafia for the enum example. One strange thing I noticed with going that route is that namespaces need to be explicitly listed for the enum variants for it to work. E.g. if the xml from the example above looked like this:
```
<Xml>
    <ns:field1 name='a'/>
    <ns:field2 name='b'/>
    <ns:field1 name='a'/>
</Xml>
```
then the enum would have to look like this:
```
    #[derive(Deserialize, PartialEq, Debug)]
    enum Field {
        #[serde(rename = "ns:field1")]
        Field1 { name: String },
        #[serde(rename = "ns:field2")]
        Field2 { name: String },
    }  
```

**Comment by reknih** [comment]
Thanks to @polarathene for sharing your workaround!

Unfortunately, the outlined approach does not work if the manually deserialized struct (like `Variable` or `Texture`) relies `$value`. The conversion will error out with the message "missing field `$value`". Do you have an idea how I could adapt this approach to remedy this?

**Example:**

```rust
#[derive(Debug, Clone, Deserialize)]
pub struct TopLevel {
    pub item: String,
    #[serde(flatten, deserialize_with = "de_macros", default)]
    pub macros: Vec<MyMacro>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct MyMacro {
    #[serde(rename = "@name")]
    pub name: String,
    #[serde(rename = "$value")]
    pub definition: String,
}

// `de_macros` omitted

fn main() {
    let test = r#"
    <doc>
        <macro name="a">...</macro>
        <item>My item</item>
        <macro name="b">...</macro>
        <macro name="c">...</macro>
    </doc>
    "#;

    let mut de = Deserializer::from_str(test);
    let top_level = TopLevel::deserialize(&mut de).unwrap();
    dbg!(top_level);
}
``` 

[Link to runnable example](https://www.rustexplorer.com/b/kz3wdk)

**Comment by Mingun** [comment]
@reknih, just use feature `overlapped-lists` to allow inserting `<item>` inside list of `<macro>`: https://www.rustexplorer.com/b/kz3wdk
