### ISSUE TITLE
`escape::unescape` treats any non-entity character sequence `&whatever;` as an error

### ISSUE THREAD

**Issue by AKhranovskiy** [tafia/quick-xml#184]
`escape::unescape` tries to recognize HTML entities so hard that it simply fails on non-entity character sequence that contains `&` and `;`.
Simple case:
```xml
<a>a&b;</a>
```
causes an error `Xml(EscapeError(UnrecognizedSymbol(2..3, Ok("b"))))`.

Should not it ignore such sequences and leave them as is?

**Comment by tafia** [comment]
I don't think we should ignore it, at least not by default.
We could have some parameters to decide to ignore it but per the *spec* this is not a valid xml.

From https://www.w3.org/TR/xml/, paragraph 2.4:
```
The ampersand character (&) and the left angle bracket (<) MUST NOT appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section. If they are needed elsewhere, they MUST be escaped using either numeric character references or the strings " &amp; " and " &lt; " respectively. The right angle bracket (>) may be represented using the string " &gt; ", and MUST, for compatibility, be escaped using either " &gt; " or a character reference when it appears in the string " ]]> " in content, when that string is not marking the end of a CDATA section.
```

I'm open to a PR to give the option to ignore this, but this shoudn't be the default.

**Comment by AKhranovskiy** [comment]
That data appears inside CDATA section so it is valid XML. Maybe escape should have context dependent rules.
