### ISSUE TITLE
(de)serializing unit struct duplicates tag

### ISSUE THREAD

**Issue by decathorpe** [tafia/quick-xml#187]
I'm working on implementing an xml-rpc client in rust, but I can't get `Value`s to deserialize correctly.

For example, integer values have this format:

```xml
<value><i4>18</i4></value>
```

I have these struct / enum definitions:

```rust
#[derive(Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename = "value")]
struct Value {
    value: Type,
}

#[derive(Debug, Deserialize, PartialEq, Serialize)]
enum Type {
    #[serde(rename = "int", alias = "i4")]
    Integer ( #[serde(rename = "$value")] i32 ),
    #[serde(rename = "boolean")]
    Boolean ( #[serde(rename = "$value")] bool ),
    #[serde(rename = "string")]
    String ( #[serde(rename = "$value")] String ),
    #[serde(rename = "double")]
    Double ( #[serde(rename = "$value")] f64),
    // ...
}
```

However, this expects duplicate `<value>` tags surrounding the `int`, like this: `<value><value><i4>18</i4></value></value>`.

If I add the `transparent` serde attribute to `Value` like this:

```rust
#[derive(Debug, Deserialize, PartialEq, Serialize)]
#[serde(transparent, rename = "value")]
struct Value {
    value: Type,
}
```

It drops **both** `value` tags and only accepts strings like `<i4>18</i4>`, where I think `transparent` should drop only the inner `value` tag.

**Comment by tafia** [comment]
Sorry for the late answer.

I made it work like this:
```rust
#[derive(Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename = "value")]
struct Value {
    #[serde(rename = "$value")]
    value: Type,
}
```

**Comment by decathorpe** [comment]
Oh, in retrospect, this solution seems kinda obvious ... Thanks a lot!

**Comment by decathorpe** [comment]
Oh, this only works for deserialisation ... :( When trying to serialize a `Value` now, I get something like this:

`<value><$value><i4>42</i4></$value></value>`

**Comment by decathorpe** [comment]
Sorry for the noise, I have to implement serialization manually anyway, since unit variants / structs are not supported. So this is not a problem for me. Thanks again!
