### ISSUE TITLE
Writer::new_with_indent() inserts white space into <![CDATA[ content tags

### ISSUE THREAD

**Issue by klausi** [tafia/quick-xml#197]
Problem: the pretty print functionality should not insert spaces new lines before and after `<![CDATA[` tags.

Example input:
```xml
<?xml version="1.0" encoding="UTF-8"?><jobs><job><jobid><![CDATA[00d46e4494e1]]></jobid></job></jobs>
```
Output with `Writer::new_with_indent(out_file, b" "[0], 2);`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jobs>
  <job>
    <jobid>
      <![CDATA[00d46e4494e1]]>
    </jobid>
  </job>
</jobs>
```
This has now changed the content of the jobid tag, which is bad.

Correct with `xmllint --format`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jobs>
  <job>
    <jobid><![CDATA[00d46e4494e1]]></jobid>
  </job>
</jobs>
```
This has correctly preserved the content of the jobid tag.

**Comment by tafia** [comment]
Thanks for opening the issue.

Do you have a specification to refer to? This is not obvious to me that the current behavior is wrong.

**Comment by klausi** [comment]
Could not find anything concrete in the XML specification, only http://xml.silmaril.ie/whitespace.html which talks about significant and insignificant whitespace.

A similar bug was reported to xml-js https://github.com/nashwaan/xml-js/issues/14 where they also decided to not indent CDATA sections.

**Comment by klausi** [comment]
Another data point is the PHP DOMDocument output which formats the same way as `xmllint` and does not indent CDATA sections. https://3v4l.org/DviGR

**Comment by klausi** [comment]
Same with Python
```python
import xml.dom.minidom

dom = xml.dom.minidom.parseString('<?xml version="1.0" encoding="UTF-8"?><jobs><job><jobid><![CDATA[00d46e4494e1]]></jobid></job></jobs>')
print(dom.toprettyxml())
```
```xml
<?xml version="1.0" ?>
<jobs>
    <job>
        <jobid><![CDATA[00d46e4494e1]]></jobid>
    </job>
</jobs>
```

Not sure if Python, PHP and xmllint all rely on the same XML parsing library, but I think these are pretty good indicators that quick-xml should do the same.

**Comment by cdwilson** [comment]
FWIW, [Altova XMLSpy](https://www.altova.com/xmlspy-xml-editor) also reformats this input as @klausi suggested:

![image](https://user-images.githubusercontent.com/14631/105612323-2c8b9e80-5d70-11eb-9b04-41e2c94dac15.png)
