### ISSUE TITLE
Strange buffer_position behaviour inside a comment

### ISSUE THREAD

**Issue by anti-social** [tafia/quick-xml#201]
Took this example from the unit tests:
```rust
r = Reader::from_str("<a><!--b>");
r.trim_text(true).check_end_names(true);

let mut buf = Vec::new();
r.read_event(&mut buf);

let mut buf = Vec::new();
r.read_event(&mut buf);
assert_eq!(r.buffer_position(), 5);
```

But if we will use a single buffer:
```rust
r = Reader::from_str("<a><!--b>");
r.trim_text(true).check_end_names(true);

let mut buf = Vec::new();
r.read_event(&mut buf);

r.read_event(&mut buf);
assert_eq!(r.buffer_position(), 4);
```

Also interesting that the `buffer_position` isn't changed for the next inputs: `"<a>\n<!--b>"`, `"<a>\n\n<!--b>"` and so on.

**Comment by tafia** [comment]
It look like there are two issues.
One may be on the comment, the other one on the `trim_text`. Let me check.

**Comment by tafia** [comment]
Could you please have a test with #206 ?
