### ISSUE TITLE
Empty Tags are ignored, even though they are part of the XML spec.

### ISSUE THREAD

**Issue by filip-minic** [tafia/quick-xml#207]
The library seems to ignore empty tags, even though they contain valuable information often and are often used. For example the following tag gets ignored in my case when parsing an XML file:
```xml
<Connector port="8080" relaxedPathChars="[]|" relaxedQueryChars="[]|{}^&#x5c;&#x60;&quot;&lt;&gt;"
                   maxThreads="150" minSpareThreads="25" connectionTimeout="20000" enableLookups="false"
                   maxHttpHeaderSize="8192" protocol="HTTP/1.1" useBodyEncodingForURI="true" redirectPort="8443"
                   acceptCount="100" disableUploadTimeout="true" bindOnInit="false"/>
```

I have tried it out and it works if there is a tag which is not self-closing, such as this one below: 
```xml
<Connector></Connector>
```

**Comment by tafia** [comment]
It should not ignore it. Have you tried to match on `Event::Empty`?

**Comment by filip-minic** [comment]
Hi, thank you for the hint, it seems that expand_empty_elements does the trick.
