### ISSUE TITLE
Extra inital empty Event::Text at parsing

### ISSUE THREAD

**Issue by fredrik-jansson-se** [tafia/quick-xml#209]
I'm parsing a simple xml snippet (<capability>urn:ietf:params:netconf:base:1.1</capability>), but I get an initial Text(BytesText { content: "" } before I get the Start(BytesStart {..}) event.

This took me by surprise :) Is this the expected behavior?

Simple reproduction here: 
https://gist.github.com/fredrik-jansson-se/ee562354fbde5ac8b8329f81ffc5c07a

**Comment by tafia** [comment]
This is what we are expecting yes. We could change this behavior but I like being able to regenerate the exact same xml if needed.
You can use the trim_text property on the reader if you want.

**Comment by dralley** [comment]
Why would it be impossible to regenerate the same XML without the empty text event?

**Comment by tafia** [comment]
it the xml starts with lot of blanks then you need a text event first to regenerate it.

**Comment by Mingun** [comment]
Duplicate of #363
