### ISSUE TITLE
Parse function for Reader

### ISSUE THREAD

**Issue by mathiaHT** [tafia/quick-xml#215]
Hi,

I am using the library the library to parse string which are not necessary representing a xml. I would be useful that the quick_xml::Reader::parse had the following signature:

```rust
pub fn parse(s: &'a str) -> Result<Reader<&'a [u8]>, Error>

Creates an XML reader from a string slice or return an error if the string is not well formatted .
```

**Comment by tafia** [comment]
The reader is lazy, it won't do anything before you actually start iterating on events (`read_event`). I don't think it can tell you in advance if the xml is correct or not.
