### ISSUE TITLE
How does the performance compare to VTD XML ?

### ISSUE THREAD

**Issue by stuaxo** [tafia/quick-xml#228]
Hi,
   VTD-XML (a non-rust lib) says on a "Core2 2.5Ghz Desktop, VTD-XML outperforms DOM parsers by 5x~12x, delivering 150~250 MB/sec per core sustained throughput."

But I don't have access to that hardware, do you have any idea how it compares to quick-xml ?

Cheers
Stuart

**Comment by tafia** [comment]
I don't know about VTD-XML and looking at the website I don't think they really compare.

quick-xml is a bare pull parser xml while VTD-XML seems to be much more (a new serialization format(?) a xpath selector etc ...).
I can't be sure but I don't see any reason why quick-xml would be slower than VTD-XML with regular xmls.

**Comment by stuaxo** [comment]
Thanks :)
