### ISSUE TITLE
deserializing xml to serde_json::Value doesn't work

### ISSUE THREAD

**Issue by ozgrakkurt** [tafia/quick-xml#231]
I am trying to convert xml to json by serializing xml to serde_json::Value with quick xml but it doesn't work. I have this code:
```rust
let value: serde_json::Value = quick_xml::de::from_str("<root><val>15</val></root>").unwrap();
let json_body = serde_json::to_string(&value).unwrap();
println!("{}", json_body);
```
It prints: `{"val":{}}`.
I would expect it to print `{"val":15}` or `{"val":"15"}`.

code is [here](https://github.com/ozgrakkurt/quick_xml_json/blob/master/src/main.rs).

**Comment by s97712** [comment]
+1

**Comment by ozgrakkurt** [comment]
This is caused by the deserializer implementation which implements  deserialize_any by calling deserialize_struct. Since serde_json::Value doesn't have "$value" field we can't get the value between the tags.

**Comment by Mingun** [comment]
This is duplicate of #185.
