### ISSUE TITLE
Serialize struct as children of struct name and not attributes.

### ISSUE THREAD

**Issue by tomgie** [tafia/quick-xml#245]
Is there any way to serialize a struct as children instead of attributes? An example of this would be:
```xml
<MyStruct>
    <ValueOne>A</ValueOne>
    <ValueTwo>B</ValueTwo>
</MyStruct>
```

**Comment by quebin31** [comment]
Currently it seems that there's no way to tell the serializer how to treat different fields, I was thinking on a trait (e.g. `Xml`) that should be derived and adds the ability to do something like this:


```rs
#[derive(Serialize, XML)]
pub struct MyStruct {
    #[xml(attr)]
    something: String,

    #[serde(rename = "Child")]
    #[xml(child)]
    child: String,
}
```

Serializing into:

```xml
<MyStruct something="A">
    <Child>B</Child>
</MyStruct>
```

**Comment by tafia** [comment]
It could probably work but I think it is really not trivial.

**Comment by quebin31** [comment]
@tafia yep, it's not trivial, I tried to take hands-on the code but not success, meanwhile I was using the fork from #251

**Comment by lukts30** [comment]
Could a feature flag be introduced to just make every struct member a child instead of an attribute?
This seems to be the default for pre 0.19. Every newer version breaks serialisation for me since everything is now an attribute instead.

Essentially, I want to opt out of *0.19.0: (Serde) Serialize basic types as attributes (breaking change)*

**Comment by tafia** [comment]
I'm ok for the feature flag (probably defaulting to attributes).

**Comment by woodworker** [comment]
Would this be solved with the `#[serde(rename = "$value")]` 

As seen in https://github.com/tafia/quick-xml/blob/a4be48431a2c512683538b81d7ee037af70d5cce/tests/serde_roundtrip.rs#L23-L26 and https://github.com/tafia/quick-xml/blob/a4be48431a2c512683538b81d7ee037af70d5cce/tests/serde_roundtrip.rs#L59-L69

**Comment by tomgie** [comment]
> Currently it seems that there's no way to tell the serializer how to treat different fields, I was thinking on a trait (e.g. `Xml`) that should be derived and adds the ability to do something like this:
> 
> ```rust
> #[derive(Serialize, Xml)]
> pub struct MyStruct {
>     #[xml(attr)]
>     something: String,
> 
>     #[serde(rename = "Child")]
>     #[xml(child)]
>     child: String,
> }
> ```
> 
> Serializing into:
> 
> ```
> <MyStruct something="A">
>     <Child>B</Child>
> </MyStruct>
> ```

I think this would be the ideal situation. I wouldn't even know where to begin implementing the derive and other things.

**Comment by solita-jaakkoha** [comment]
Latest master now allows `<root><first>value</first><second>value</second></root>` to be (de)serialized with the special name prefix `$unflatten=`:

```
struct Root {
    #[serde(rename = "$unflatten=first")]
    first: String,
    #[serde(rename = "$unflatten=second")]
    other_field: String,
}
```

**Comment by tafia** [comment]
Closing it. Feel free to reopen if needed.
