### ISSUE TITLE
Builds of 0.21 are much slower, wasm builds cause massive memory use in rustc

### ISSUE THREAD

**Issue by adrian17** [tafia/quick-xml#255]
This was probably caused by https://github.com/tafia/quick-xml/pull/239/files#diff-0acc5298e8580ddde57f322c2f6b70406f8d2b13acd0bebc4125428a66afc585 .

Reproduction:
```
git clone https://github.com/tafia/quick-xml.git
cd quick-xml
git checkout 1961d8e
```
```
cargo build --release
```
Builds in 40s (2s before this commit)
```
cargo build --release --target=wasm32-unknown-unknown
```
After 1-2 minutes rustc's memory use starts increasing to 4+ GB, causing my machine to start swapping. (builds in 2s before this commit)

You can also see the effect on GH Actions workers - a PR that bumped quick-xml dependency seems to have significantly increased build times (by 6-7min) on some configurations.

Compare:
https://github.com/ruffle-rs/ruffle/runs/1825148297
https://github.com/ruffle-rs/ruffle/runs/1825150290

**Comment by adrian17** [comment]
(sounds like this might also warrant a bug report to rustc itself?)

**Comment by tafia** [comment]
Thanks for reporting this! It is definitely not something I'm tracking right now.

**Comment by adrian17** [comment]
The only reason I noticed was because this OOM'd rustc on the machine I build on ;)

**Comment by tafia** [comment]
Move the html escaping behind a feature flag. I don't know if this is something you needed to rely on but I bet for most people they don't need it (it is a recent change).

**Comment by adrian17** [comment]
FYI, I reported https://github.com/rust-lang/rust/issues/81757 .

**Comment by torhovland** [comment]
I ran into a similar issue. My code at https://github.com/torhovland/surway/tree/6a44024d89e1b55ad43700317e7d86f389cce36b builds fine in Release mode, but when running `trunk build` in Debug mode, I get:

```
wasm-bindgen call returned a bad status error: failed to parse input file as wasm

Caused by:
    locals exceed maximum (at offset 1029067)
```

Downgrading quick-xml from 0.21 to 0.20 fixes it.
