### ISSUE TITLE
How to pretty print a xml from a struct ?

### ISSUE THREAD

**Issue by patrickelectric** [tafia/quick-xml#264]
So, I have a struct like:
```rust
#[derive(Debug, Default, Serialize)]
struct Test {
    name: String,
    age: String,
    state: State,
}

#[derive(Debug, Default, Serialize)]
struct State {
    good: bool,
}

println!("{:?}", to_string(&Test{name: "potato".into(), age: "42".into(), state: State::default()}).unwrap());
```

And it results in:
```xml
"<Test name=\"potato\" age=\"42\"><state good=\"false\"/></Test>"
```

Is there any way to have a pretty print with it ? I can see that there is the Writer, but not sure if that is the real scenario and how to accomplish it without a bunch of unnecessary code.

**Comment by patrickelectric** [comment]
I was waiting for something like:
```xml
<Test name="potato" age="42">
   <state good="false" />
</Test>
```

**Comment by Albert666232** [comment]
I am waiting for the answer,too.  :)

**Comment by tafia** [comment]
There is no one-line way to do it yet. Someone needs to implement it and I'll happily merge it.

**Comment by lwilli** [comment]
I would also be interested in an easy way to pretty print XML. My use case is not with a struct, but with a given XML string.

I came up with a quick solution to prettify an XML string by reading it in and then writing it out with indents: https://gist.github.com/lwilli/14fb3178bd9adac3a64edfbc11f42e0d. Probably not the best, but it [mostly](https://github.com/tafia/quick-xml/issues/276) works.

**Comment by Mingun** [comment]
Duplicate of #361
