### ISSUE TITLE
Reader fails to parse single tag elements with attributes

### ISSUE THREAD

**Issue by sergeken** [tafia/quick-xml#267]
The following working example reproduces the problem.

For the string "pass", the client elements get correctly parsed and triggers both "start" and "end" events.
For the string "fails", the client elements don't get parsed and no "start" and "end" events are triggered.
The expected behaviour is that both strings yield the same results.

```
use std::str;

use quick_xml::events::Event;
use quick_xml::Reader;

fn read(text: &str) {
    let mut reader = Reader::from_str(text);
    reader.trim_text(true);
    loop {
        match reader.read_event(&mut Vec::<u8>::new()) {
            Ok(Event::Eof) => break,
            Ok(Event::Start(ref e)) => {
                dbg!("start");
                dbg!(str::from_utf8(e.name()).unwrap());
                match e.name() {
                    b"client" => (),
                    _ => (),
                }
            }
            Ok(Event::End(ref e)) => {
                dbg!("end");
                dbg!(str::from_utf8(e.name()).unwrap());
                match e.name() {
                    b"client" => (),
                    _ => (),
                }
            }
            _ => (),
        }
    }
}

fn main() {
    let pass = r#"
    <?xml version="1.0"?>
      <clients>
        <client id="1" first="John" last="Doe">
        </client>
        <client id="2" first="Jimmy" last="Doe">
        </client>
      </clients>
    "#;
    let fail = r#"
    <?xml version="1.0"?>
      <clients>
        <client id="1" first="John" last="Doe"/>
        <client id="2" first="Jimmy" last="Doe"/>
      </clients>
    "#;
    read(&pass);
    read(&fail);
}
```

It produces the following output

> [src\main.rs:13]` "start" = "start"
> [src\main.rs:14] str::from_utf8(e.name()).unwrap() = "clients"
> [src\main.rs:13] "start" = "start"
> [src\main.rs:14] str::from_utf8(e.name()).unwrap() = "client"
> [src\main.rs:21] "end" = "end"
> [src\main.rs:22] str::from_utf8(e.name()).unwrap() = "client"
> [src\main.rs:13] "start" = "start"
[> src\main.rs:14] str::from_utf8(e.name()).unwrap() = "client"
> [src\main.rs:21] "end" = "end"
> [src\main.rs:22] str::from_utf8(e.name()).unwrap() = "client"
> [src\main.rs:21] "end" = "end"
> [src\main.rs:22] str::from_utf8(e.name()).unwrap() = "clients"
> [src\main.rs:13] "start" = "start"
> [src\main.rs:14] str::from_utf8(e.name()).unwrap() = "clients"
> [src\main.rs:21] "end" = "end"
> [src\main.rs:22] str::from_utf8(e.name()).unwrap() = "clients"

**Comment by tafia** [comment]
Please see [expand_empty_elements](https://docs.rs/quick-xml/0.21.0/quick_xml/struct.Reader.html#method.expand_empty_elements)

**Comment by sergeken** [comment]
Great!  Works indeed.
Any reason why the default is false?  I would have expected the opposite as to me it is a breaking default.

**Comment by tafia** [comment]
The default generally leans toward more efficient binaries. `Empty` elements require less work even if that may get optimized away.
