### ISSUE TITLE
serde deserialize, attribute and child element share the same name

### ISSUE THREAD

**Issue by void-dragon** [tafia/quick-xml#293]
i have a funny problem parsing COLLADA xml documents:

```xml
<skin source="#Cylinder_002-mesh">
        <source id="Armature_JointBase_001-skin-joints"> .. </source>
</skin>
```
And i is not clear how the Rust code has to look to parse something like this.

My naive approach was something like this:
```rust
#[derive(Deserialize)]
pub struct Skin {
    #[serde(rename = "source")]
    pub sources: Vec<SkinSource>,
}

#[derive(Deserialize)]
pub enum SkinSource {
    Source{id: String},
    Attr(String),
}
```
But this did not work.

**Comment by Mingun** [comment]
Since [version 0.27.0](https://github.com/tafia/quick-xml/blob/master/Changelog.md#0270----2022-12-25) this is solved by prepending `@` to the names of attributes. The original task can be solved by this types:
```rust
#[derive(Deserialize)]
pub struct Skin {
    #[serde(rename = "@source")]
    pub source: String,

    #[serde(rename = "source")]
    pub sources: Vec<SkinSource>,
}

#[derive(Deserialize)]
pub struct SkinSource {
    #[serde(rename = "@id")]
    id: String,
}
```

Fixed by #490.
