### ISSUE TITLE
A way to collect attributes on deserialization

### ISSUE THREAD

**Issue by xamgore** [tafia/quick-xml#296]
If someone would like to get the text node, `$value` may be used. Now, let's imagine there is a node with arbitrary attributes:

```xml
<person key1="..." key2="..." key3="...">
  ...
</person>
```

Is there any way to define serde types in a way, that would allow collecting attributes into a vector or map?

```rust
#[derive(PartialEq, Deserialize)]
struct Person {
  #[serde(rename = "$attributes")]
  attributes: Vec<(String, String)>
  // ...
}
```

**Comment by cozyGalvinism** [comment]
I would also love to be able to access attributes like this, +1

**Comment by xamgore** [comment]
@cozyGalvinism I haven't tested it yet, but [flattening](https://serde.rs/attr-flatten.html#capture-additional-fields) may help.

**Comment by cozyGalvinism** [comment]
Flattening doesn't work here, because it doesn't flatten attributes, at least to my knowledge.

**Comment by Ben-Lichtman** [comment]
> Disregard my previous statement, flattening does seem to work in that way.

Could you provide an example of this please, I am unable to reproduce this solution, thanks.

**Comment by cozyGalvinism** [comment]
> > Disregard my previous statement, flattening does seem to work in that way.
> 
> Could you provide an example of this please, I am unable to reproduce this solution, thanks.

```rust
    use serde::{Deserialize, Serialize};
    use std::collections::HashMap;

    #[derive(Serialize, Deserialize, Debug)]
    #[serde(rename = "root")]
    struct XmlRoot {
        #[serde(flatten)]
        attributes: HashMap<String, String>,

        #[serde(rename = "$value")]
        value: String,
    }

    #[test]
    fn test_flattening() {
        let xml = r#"<root attribute1="value1" attribute2="value2">
            Hello World!
        </root>"#;
        let xml_root: XmlRoot = quick_xml::de::from_str(xml).unwrap();
        println!("{:?}", xml_root);
    }
```
will get you `XmlRoot { attributes: {"attribute1": "value1", "attribute2": "value2"}, value: "Hello World!" }`.

**Comment by Ben-Lichtman** [comment]
Hmm, ok this works, but when I serialize this back into a string I get the wrong result

**Comment by xamgore** [comment]
> @cozyGalvinism: Though like this, you will lose the ability to parse attributes with the same name. For that, you would need to create your own map type, possibly over `Vec<(String, String)>`.

One could use [`MultiMap`](https://lib.rs/crates/multimap).

> @Ben-Lichtman: when I serialize this back

I believe you'll have to implement a custom serializer.
