### ISSUE TITLE
Improve API for creating new elements

### ISSUE THREAD

**Issue by matt2xu** [tafia/quick-xml#3]
Instead of Element::new(name, attributes), we could do separate the text and attributes part:

  1. Element::new(text) // works for any kind of element: text, comment, start, end...
  2. element.add_attributes(iter) // only useful for start elements

This way, no need to pass an empty iterator for elements where attributes don't make sense (text or comment).

I would also change the Element::new to use an AsRef<[u8]> for the name, to allow faster/easier creation of elements from existing ones.

**Comment by tafia** [comment]
Looks like a good idea.

For the attributes, I'd prefer `extend_attributes(iter)` to consume an iterator (a-la `Vec`). 
A `push_attribute` could be useful too (could be internally used by the extend version) because one does not always have an iterator at hand.

**Comment by matt2xu** [comment]
:+1: I'll look into it.

**Comment by tafia** [comment]
closed by #5
