### ISSUE TITLE
$unflatten breaks with namespaces and nesting

### ISSUE THREAD

**Issue by mohe2015** [tafia/quick-xml#305]
Reproducers at https://github.com/mohe2015/quick-xml-bugs. Hopefully I didn't mess anything up.

Crossref https://github.com/tafia/quick-xml/pull/298

cc @solita-jaakkoha

**Comment by tafia** [comment]
Thanks for the code!
Having a look

**Comment by tafia** [comment]
I've just made a fix here (#306), could you have a try?
