### ISSUE TITLE
[Question] How to use a stream (future) as reader?

### ISSUE THREAD

**Issue by harscoet** [tafia/quick-xml#327]
Sorry if it's obvious, I'm pretty new in Rust development!

I use [bytes_stream](https://docs.rs/reqwest/0.11.6/reqwest/struct.Response.html#method.bytes_stream) method from [reqwest](https://docs.rs/reqwest/0.11.6/reqwest/ ) to stream a file from [google cloud storage](https://cloud.google.com/storage), this method returns `impl Stream<Item = Result<Bytes>>`

How can I consume this stream with `quick-xml`? This lib seems to not handle async if I understand the PR https://github.com/tafia/quick-xml/pull/314 so maybe I should wait this feature

Thanks for the help!

**Comment by erikpols** [comment]
@harscoet did you ever find an answer or workaround?
