### ISSUE TITLE
The decode logic should be done on Cows instead of slices

### ISSUE THREAD

**Issue by stevenroose** [tafia/quick-xml#336]
Just like I did https://github.com/tafia/quick-xml/pull/330 for unescaping, the same should be done for decoding. The Cow's that are currently returned make very little sense, because they usually borrow into ephemeral data so they will always eventually have to be converted into owned data. I'm thinking of having some kind of `Bytes`-based implementation that might allow us to not have to re-allocate so often when we already have a `Cow::Owned`.

**Comment by dralley** [comment]
https://github.com/tafia/quick-xml/issues/158 will address this
