### ISSUE TITLE
Attributes are not zero copy

### ISSUE THREAD

**Issue by Dav1dde** [tafia/quick-xml#352]
```rust
use std::borrow::Cow;
use serde::Deserialize;

#[derive(Deserialize)]
struct Root<'a> {
    #[serde(borrow)]
    rattr: Cow<'a, str>,
}

const XML: &str = r#"
<Root rattr="rattr">
</Root>
"#;

fn main() {
    let r: Root = quick_xml::de::from_str(XML).unwrap();

    assert!(matches!(r.rattr, Cow::Borrowed(_)));
}
```

This assert fails.

I assume this is because of this call to `visit_str` (which should be `visit_borrowed_str`):
https://github.com/tafia/quick-xml/blob/master/src/de/escape.rs#L79

```rust
    fn deserialize_str<V>(self, visitor: V) -> Result<V::Value, Self::Error>
    where
        V: Visitor<'de>,
    {
        let unescaped = self.unescaped()?;
        #[cfg(not(feature = "encoding"))]
        let value = self.decoder.decode(&unescaped)?;

        #[cfg(feature = "encoding")]
        let value = self.decoder.decode(&unescaped);
        visitor.visit_str(&value) // <-- visit_borrowed_str here
    }
```

Unfortunately I was not able to make this work due to lifetimes not matching

**Comment by dralley** [comment]
Is this related to https://github.com/tafia/quick-xml/pull/337?

**Comment by Mingun** [comment]
No, #337 not fixes that because it does not touch `de/map.rs`. Actually, not only attributes are not zero-copy, elements too.

#376 fixes problem for attributes, but it still exist for elements. When I rebase it to my fork I'll look closer to this problem.

**Comment by Mingun** [comment]
Attributes are zero-copy in current [master](https://github.com/tafia/quick-xml/tree/b6e376b5e263a611ed7ac0c7d3d7a277b76deda8), the testcase will be added in #571
