### ISSUE TITLE
Add a structure to facilitate .as_str()/.as_bytes()

### ISSUE THREAD

**Issue by matt2xu** [tafia/quick-xml#4]
At the moment, Element has two methods as_bytes() and as_str() to allow access to raw bytes or conversion to UTF-8 strings. Also, Element has no way to access the all contents (from start to end) as either raw or str, only as String (which is incidentally why the writer cannot use write_wrapped_str for start elements). Attributes, on the other hand, iterates over raw keys with converted strings. Maybe we could introduce a "Text" structure or something similar, that:

  - automatically converts to [u8] (this is what the Deref trait allows if I understand correctly)
  - as a as_str() method to do the explicit conversion
  - then Attributes would iterate over (Text, Text), and Element could have two functions name() that returns a Text over the bytes from start to name_end, and content() that returns a Text over the bytes from start to end.

Not sure if Text is a good name, but you get the idea :-)

**Comment by tafia** [comment]
LGTM!

**Comment by matt2xu** [comment]
I tried that, but it turned out to be too verbose and complicated. I went a different route: use only [u8] for name() and content() methods, and use an AsStr trait that implements as_str() for [u8]. Not sure if the trait is worth to have or not. Let me know what you think: https://github.com/matt2xu/quick-xml/commit/44a245bd34151decb94b9226ddf7f47378d5bade

**Comment by tafia** [comment]
I don't know how useful is the `content` method, I can only see the scenario where we want to copy the entire element, perhaps we can have `Element` deref to `&[u8]` so we can `copy_from_slice` directly on `&Element`. But I'm not sure it won't interfere with some other methods ...

**Comment by matt2xu** [comment]
The content method is useful to get the whole element, including attributes, for instance in the writer (there is no longer a different method for writing start elements) and for the Debug impl. Plus it seems more natural to get the content of a Text or Comment Event rather than their name, it makes the intent of the code clearer in my opinion.

**Comment by tafia** [comment]
I think `content` is ok.
Can you do a PR ?

**Comment by matt2xu** [comment]
Sure!

**Comment by tafia** [comment]
closed by #6

**Comment by tafia** [comment]
For people having compilation issue, #6 breaks existing code. To fix you'll need to:
- replace `as_bytes` with `name`
- replace `as_str` with `content().as_str()` or `name().as_str()` depending on your use case
