### ISSUE TITLE
Add and improve benchmarks for escape / unescape routines

### ISSUE THREAD

**Issue by dralley** [tafia/quick-xml#404]
Currently there are none for escaping text, and very few for unescaping text, which don't actually exercise the code very heavily.

From looking at flamegraphs of my program, escaping text tends to be very expensive currently and is a good optimization candidate.  Not sure if that is broadly generalizable or specific to my program, but it's worth mentioning.

It would be appropriate to consider small, medium and large inputs (attribute-sized inputs vs text) with varying numbers of escapable characters.

**Comment by Mingun** [comment]
> From looking at flamegraphs of my program,

It would be useful if you could at least add a note to the readme, how to gather this information.

**Comment by dralley** [comment]
https://github.com/flamegraph-rs/flamegraph

It is pretty simple, the readme (of that tool) explains what you need to know.

**Comment by dralley** [comment]
![Screenshot from 2022-06-25 11-59-48](https://user-images.githubusercontent.com/2751996/175781676-162bbe02-3c18-4470-a014-bb7a42018f6d.png)

This is the output from generating a flamegraph on a criterion benchmark for writing some XML (to memory, no IO) where many attribute values need to be escaped.

**Comment by Mingun** [comment]
Yes, I know what is a flamegraph. I mean, that you could make a PR to the readme with instructions: "install that, run that, see that". Then it will be easily for others (who could be interested in contributing) to get their right development environment faster :)
