### ISSUE TITLE
Other charsets are not supported

### ISSUE THREAD

**Issue by Kilte** [tafia/quick-xml#46]
Looks like it works with UTF-8 only.
At least I can confirm that it doesn't work with KOI8-R.

**Comment by tafia** [comment]
Thank you for opening the issue. 

Could you provide me with a broken XML (which I'll use for unit tests as well).

**Comment by tafia** [comment]
@Kilte I have just submitted a PR to support other charsets.

The api is not as nice as we could expect. I tried to explain the motivation in the PR.
Could you please try it out and give me some feedbacks?

**Comment by tafia** [comment]
#52 is about to be merged. I believe it'll close this issue then.

**Comment by tafia** [comment]
merged
