### ISSUE TITLE
I can't get my old code to work with 0.24+

### ISSUE THREAD

**Issue by ghost** [tafia/quick-xml#482]
Hello,

There have been breaking changes in 0.24+, and I've spent 30 min trying to port my old code, which was working perfectly fine in previous versions. I think I managed to solve most of the compile errors, but the following line has given me a huge headache:

`let elem = quick_xml::events::BytesStart::owned(e.name().to_vec(), e.name().len());`

My old brain can't understand how to port this line to 0.24+. I did read the [Changelog](https://github.com/tafia/quick-xml/blob/master/Changelog.md), which hints at using:

`BytesStart::from_content(impl Into<Cow<str>>, usize)`

instead of:

`BytesStart::owned(impl Into<Vec<u8>>, usize)`

but since their parameters are different, I didn't find this hint particularly helpful. I am probably just dumb.

If someone can fully convert the line for me, and deliver me from my misery, I would really appreciate.

Thank you in advance!

**Comment by dralley** [comment]
I agree that in this particular version, it's a bit ergonomically challenging.  We're working on improving that by consolidating on `&str` and `String` everywhere, but it's not there yet.

First question, what type is `e`?  If it's already a `BytesStart` you probably don't need to create a new event in the first place.

But assuming there is a reason, you have `e.name()` which returns a `QName<'_>` which is a simple wrapper around raw bytes.  So you need to go from raw bytes to something that implments `Into<Cow<str>>`.  You should either use `String::from_utf8()` or `std::str::from_utf8()` for that.

**Comment by dralley** [comment]
No problem!  It should become simpler again in a future release.
