### ISSUE TITLE
Exclude extra files from package

### ISSUE THREAD

**Issue by TehPers** [tafia/quick-xml#488]
`quick-xml` 0.25.0 is 3.2MB on disk for me (Windows), but most of that is from the tests folder. As far as I'm aware, that folder, the benches folder, and some other files aren't really needed to use the package and mostly exist for development of the package itself.

Here's a list of files that I think could be excluded (without knowing a lot about how the package is developed, to be fair):
- `tests/*`
- `benches/*`
- `.github/*`
- `examples/*` (some users might want this)
- `.git*`
- `Cargo.lock` (not 100% sure if this needs to be excluded honestly)
- `Changelog.md` (some users might want this)

Alternatively, the following files can be *included*:
- `src/*`
- `README.md`
- `LICENSE-MIT.md`
- `Changelog.md` (if people find this useful)
- `example/*` (if people find this useful)

This can be done [using `include` and `exclude` in the `[package]` section](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) of the Cargo.toml.

**Comment by Mingun** [comment]
That would be great! Mind do a PR?

**Comment by Mingun** [comment]
Most of the space is occupied by documents in `tests/documents`. If no better solution will found, we can exclude only them.

> I can open up a draft PR with what I have if you'd like. It's literally a single-line change so far:

You can do that now if you like, or after you finishes your findings. Or you can post the results here and I'll do PR by myself.

**Comment by dralley** [comment]
Alternatively we could use `cfg` in each particular file, instead of declaring them in Cargo.toml

**Comment by Mingun** [comment]
This [question](https://users.rust-lang.org/t/cargo-publish-with-excluded-benchmark-fails-validation/53444) seems promising -- need only explicitly add `path` to tests and benchmarks and then they could be excluded. I think this is better than `cfg` because with `cfg` cargo will build files even when they will not contains tests.

**Comment by TehPers** [comment]
That looks promising, thanks for the help! I'll open a PR in a few minutes.
