### ISSUE TITLE
How to construct a Reader from &[u8]

### ISSUE THREAD

**Issue by ngugcx** [tafia/quick-xml#491]
Get a xml data of type &[u8], how can I construct a Reader?
```
let data: &[u8] = from_somewhere();
let reader = Reader::from_str(std::str::from_utf8(data)?);
```
Then quick-xml converts it into bytes in from_str:
```
Self::from_reader(s.as_bytes())
```

**Comment by dralley** [comment]
You can just use `Reader::from_reader()` directly, or else do what you've done above.

**Comment by ngugcx** [comment]
Oops, I thought from_reader is from a `Reader`.

**Comment by dralley** [comment]
Nope, it means "from something which implements the `Read` trait"

**Comment by Mingun** [comment]
> or else do what you've done above.

Minor note: your original code will work only if your `from_somewhere();` returns data in UTF-8 encoding
