### ISSUE TITLE
read label content

### ISSUE THREAD

**Issue by cn-hew** [tafia/quick-xml#502]
How should I read the corresponding attributes in these tags? I haven't found any relevant examples in the document.

for status or path？

```xml
<Testcase UniqueID="b4fd3ae92630ce356cfd98f1d64dbb54" path="TC0305_FSI_FM_SignalMonitoring-FAULT_EPBi_187_ESP_TCSFailStatus.1666008537" relativePathNorm="T0305_FSI_FM_SignalMonitoring\TC0305_FSI_FM_SignalMonitoring-FAULT_EPBi_187_ESP_TCSFailStatus.1666008537" status="passed">
  <TesterComment text=""/>
  <FailureData TestStep="" TestStepResult=""/>
  <Starttime date="2022-10-17" time="20:08:56"/>
  <Endtime date="2022-10-17" time="20:09:42"/>
</Testcase>
```

**Comment by Mingun** [comment]
It depends on what API you want to use: low-level or serde.

The basic example for low-level API is here: https://docs.rs/quick-xml/latest/quick_xml/reader/struct.Reader.html#examples

The examples for serde API does not written yet, some drafts can be found here: #369. They are outdated for master, because fields mapped to attributes should start fro `@`. The basic mapping would be:

```rust
#[serde(Deserialize)]
struct Testcase {
  // attributes
  #[serde(rename = "@path")] // not needed in 0.26, required in master
  path: String,

  #[serde(rename = "@status")] // not needed in 0.26, required in master
  status: String,

  // elements
  #[serde(rename = "TesterComment")]
  tester_comment: TesterComment,
}
#[serde(Deserialize)]
struct TesterComment {
  #[serde(rename = "@path")] // not needed in 0.26, required in master
  text: String,
}
```

**Comment by cn-hew** [comment]
> 

I resolved it with examples, but I have many <Testcase>. How do I filter the part that needs to be retained according to the <Testcase> attribute
`
----------------
[Ok(Attribute { key: "UniqueID", value: Borrowed("be49e2753828384fc96396b7aa4e45aa") }), Ok(Attribute { key: "path", value: Borrowed("TC0305_FSI_FM_SignalMonitoring-FAULT_EPBi_206_ESP_LatAccel.1666008774") }), Ok(Attribute { key: "relativePathNorm", value: Borrowed("T0305_FSI_FM_SignalMonitoring\TC0305_FSI_FM_SignalMonitoring-FAULT_EPBi_206_ESP_LatAccel.1666008774") }), Ok(Attribute { key: "status", value: Borrowed("failed") })]
----------------
[Ok(Attribute { key: "UniqueID", value: Borrowed("be49e2753828384fc96396b7aa4e45aa") }), Ok(Attribute { key: "path", value: Borrowed("TC0305_FSI_FM_SignalMonitoring-FAULT_EPBi_206_ESP_LatAccel.1666008821") }), Ok(Attribute { key: "relativePathNorm", value: Borrowed("T0305_FSI_FM_SignalMonitoring\TC0305_FSI_FM_SignalMonitoring-FAULT_EPBi_206_ESP_LatAccel.1666008821") }), Ok(Attribute { key: "status", value: Borrowed("passed") })]
----------------
[Ok(Attribute { key: "UniqueID", value: Borrowed("38eb618c1c9cbcbc10fc00880ebb25a1") }), Ok(Attribute { key: "path", value: Borrowed("TC0305_FSI_FM_SignalMonitoring-FAULT_EPBi_206_ESP_LongAccel.1666008867") }), Ok(Attribute { key: "relativePathNorm", value: Borrowed("T0305_FSI_FM_SignalMonitoring\TC0305_FSI_FM_SignalMonitoring-FAULT_EPBi_206_ESP_LongAccel.1666008867") }), Ok(Attribute { key: "status", value: Borrowed("passed") })]
----------------
`

**Comment by Mingun** [comment]
Hm, for now it looks like your question more about general programming practices rather than of quick-xml API. Could you clarify your question: what you have and what you want to get?

**Comment by cn-hew** [comment]
Thank you for answering my question patiently. My goal is to filter the XML files on the diagram and then convert them into a json dictionary. At present, I want to use the quick-xml API to filter the parts I want.

**Comment by Mingun** [comment]
I think, the use of serde API would be preferred. Here is an example, how to collect tests that failed:

```rust
#[derive(Debug, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "lowercase")]
enum Status {
  Passed,
  Failed,
}

#[derive(Debug, PartialEq, Eq, Deserialize)]
struct TestCase {
  //#[serde(rename = "UniqueID")]// 0.26
  #[serde(rename = "@UniqueID")] // master
  id: String,

  #[serde(rename = "@status")]   // master
  status: Status,
}
let mut de = Deserializer::from_str("
    <Testcase UniqueId='1' status='completed'/>
    <Testcase UniqueId='2' status='failed'/>
    <Testcase UniqueId='3' status='completed'/>
");

let mut cases = Vec::new();
while let Ok(item) = TestCase::deserialize(&mut de) {
  if item.status == Status::Failed {
    cases.push(item);
  }
}

assert_eq!(cases, vec![
  TestCase { id: "2".to_string(), status: Status::Failed },
]);
```
