### ISSUE TITLE
[Question]: Deserialize optional vector

### ISSUE THREAD

**Issue by sandersantema** [tafia/quick-xml#510]
Afaik the following line in `Cargo.toml` should mean that I'm using the latest git version of `quick-xml`:
```
quick-xml = { git = "https://github.com/tafia/quick-xml", features = ['serialize']}
```
Although I've put question in the title this issue might be a bug, but I can't tell whether I'm doing something wrong or if it is indeed a bug.

I've got the following xml:

```xml
<ENTRY>
  <CUE_V2 NAME="foo"></CUE_V2>
  <CUE_V2 NAME="bar"></CUE_V2>
</ENTRY>
```

And I've got the following struct to deserialize:
```rust
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename = "ENTRY")]
struct Entry {
    #[serde(rename = "CUE_V2")]
    cues: Vec<Cue>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde_with::serde_as]
struct Cue {
    #[serde(rename = "@NAME")]
    name: String,
}
```

This works but is incorrect since the cue vector should be optional like so:
```rust
#[derive(Debug, Serialize, Deserialize)]
#[serde(rename = "ENTRY")]
struct Entry {
    #[serde(rename = "CUE_V2")]
    cues: Option<Vec<Cue>>,
}
```

But this gives the error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedEnd([69, 78, 84, 82, 89])', src/main.rs:330:56
```

There might be a trivial solution, but after two days of using rust in total I can't seem to find it :)

If I may take the opportunity to ask another unrelated question, how do I build the documentation for the git version of the package locally? I've been looking through #490 but I think having the actual documentation would be a bit better :)

**Comment by Mingun** [comment]
> But this gives the error:

Yes, this looks like a bug, I faced with it but did not dig yet. Probably related to #497. Perhaps in your case it would more useful to define `cues` as `#[serde(default)]` to get an empty vector if no elements is present.

To build the doc use the following command (powershell):
```ps
$env:RUSTDOCFLAGS="--cfg docs_rs"; cargo +nightly doc --all-features
```
(
```ps
$env:RUSTDOCFLAGS="--cfg docs_rs"; cargo +nightly doc --all-features --document-private-items
```
if you wish to learn internals and contribute to the project)

**Comment by sandersantema** [comment]
Thanks so much for the very quick answer! This workaround serves me very well. Compiling the documentation using your command works well, although the online documentation still says `0.26.0` but I think that's wrong. I can't find much about using quick-xml together with structs however, is that missing or is something going wrong on my side?

**Comment by Mingun** [comment]
> Compiling the documentation using your command works well, although the online documentation still says `0.26.0`

Yes, because we update version number when we [make a release](7c423cec23f3f8753651456be10ea9e313747b07), until that the reported version is the last released version.

> I can't find much about using quick-xml together with structs however, is that missing or is something going wrong on my side?

The documentation for serde mapping is coming. Draft in #369 (but it is outdated in some places)

**Comment by sandersantema** [comment]
Thanks again for being so helpful, with #369 I think I should be able to figure out how it works. Looking forward to whenever `0.27.0` is released :)
