### ISSUE TITLE
Allow to continue parsing after `Error::EndEventMismatch`

### ISSUE THREAD

**Issue by moy2010** [tafia/quick-xml#513]
I'm trying to parse a Netscape bookmark file which has unclosed tags (i.e. `<DL>`), and for this I'm explicitly ignoring the `EndEventMismatch` error during the parsing:

```rust
match reader.read_event() {
    Err(e) => match e {
        QuickXmlError::EndEventMismatch { expected: _, found: _ } => (),
```

The issue is that an `Eof` event immediately follows this, which causes that the reader stops parsing the rest of the document.

I couldn't find in the documentation if this behaviour is expected, hence why I'm opening the issue.

**Comment by Mingun** [comment]
I've never think about this way of reading events, but it seems to a good candidate to support. PR is welcome.

Current way to achive the same is to [disable](https://docs.rs/quick-xml/latest/quick_xml/reader/struct.Reader.html#method.check_end_names) reporting mismathed ends. Unfortunately, [the example](https://docs.rs/quick-xml/latest/quick_xml/reader/struct.Reader.html#method.read_text) that shows how you can disable this only for a part of document, is bug-prone. If you do that, the `Start` event name won't be popped out from internal stack of unclosed events and you'll get a wrong `EndEventMismatch` error after closing the first surrounding tag:
```xml
<some-tag>
  <event>
    <!-- You decided to .check_end_names(false) after seeing "<event>" -->
    ...
  </event>
  <!-- You decided to .check_end_names(true) after seeing "</event>" -->
</some-tag><!-- EndEventMismatch { expected "event", found: "some-tag" } -->

**Comment by moy2010** [comment]
Ah, thanks for pointing to that method, Mingun! In the case of parsing the Netscape bookmark file there's no need to re-enable the check for end-names since there's no surrounding tag.

As you said, it would be very error prone if that was the case and the desired behaviour was that of toggling on and off the check for end-names.
