### ISSUE TITLE
Consider publishing releases on GH

### ISSUE THREAD

**Issue by zeenix** [tafia/quick-xml#522]
It's great to see that you folks follow the good old practice of tagging releases. However, if anyone wants to follow releases of the project, it's not possible just with tags (AFAIK). I would suggest creating releases for each tag as well. The release notes can simply be copy&pasted from the relevant Changelog entry.

Just a request. Feel free to ignore and close the issue. :) No hard feelings either way. :+1:

**Comment by Mingun** [comment]
Ok, next release will be on GitHub

**Comment by zeenix** [comment]
> Ok, next release will be on GitHub

Thank you so much!
