### ISSUE TITLE
Everything is an Event::Start with utf-16 files

### ISSUE THREAD

**Issue by bbergeron0** [tafia/quick-xml#563]
I have several UTF-16 files which doesn't parse properly.

When looping with `read_event_into`, most stuff gets interpreted as a tag start, including comments, self-closing tags, CDATA, and closing tags.

OS: Gentoo Linux
quick-xml version: "0.27", no additional feature flags
Input XML: These files are Skyrim "FOMod" files used for modding. [This archive](https://www.nexusmods.com/skyrimspecialedition/mods/2424?tab=files&file_id=35608) contains an UTF-16 encoded XML file named "EnhancedLightsandFX 3.06/fomod/ModuleConfig.xml" which doesn't parse properly with quick-xml.

**Comment by dralley** [comment]
Unfortunately only single byte encodings are supported at the moment https://github.com/tafia/quick-xml/blob/master/src/encoding.rs#L31

The work to eventually enable it is tracked here https://github.com/tafia/quick-xml/issues/158, I will close this issue as a duplicate.

I have a PR where I got it working, however, I was roadblocked by the difficulty of async support and my free time mostly drying up for a few months.
