### ISSUE TITLE
Alternative to `Writer::write()`

### ISSUE THREAD

**Issue by Weasy666** [tafia/quick-xml#575]
Hello!

I want to upgrade the `quick-xml` dependency of our local `samael` clone and ran into the problem that `Writer::write()` is now private. Could you please tell me, what the alternative would be to use here https://github.com/njaremko/samael/blob/37b54c5954a566dffeabd030b082f96b00dbdc9d/src/signature.rs#L84 ?

**Comment by Mingun** [comment]
`writer.write_event(Event::Text(...))` or `writer.write_event(Event::CData(...))`

**Comment by Weasy666** [comment]
Sorry for the late reply. I tried your suggestions, but they don't work.
THe code here https://github.com/njaremko/samael/blob/37b54c5954a566dffeabd030b082f96b00dbdc9d/src/signature.rs#L292 produced this result

```xml
<ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms>
```
in version `0.23`, but now in version `0.28` it produces this result, where the `Transform` nodes are escaped

```xml
<ds:Transforms>&lt;ds:Transform Algorithm=&quot;http://www.w3.org/2000/09/xmldsig#enveloped-signature&quot;/&gt;&lt;ds:Transform Algorithm=&quot;http://www.w3.org/2001/10/xml-exc-c14n#&quot;/&gt;</ds:Transforms>
```

Is there a way to replicate that behavior (aka write a string/content unescaped) with the current version?

**Comment by Mingun** [comment]
The intended and more efficient way to combine pieces of XML is to pass `Writer` and write to it on each level, like this:
```rust
impl Transform {
    pub fn to_xml<W: Write>(&self, writer: &mut Writer<W>) -> Result<(), Box<dyn Error>> {
        let mut root = BytesStart::new(TRANSFORM_NAME);
        root.push_attribute(("Algorithm", self.algorithm.as_ref()));

        if let Some(xpath) = &self.xpath {
            writer.write_event(Event::Start(root.borrow()))?;

            writer
                .create_element(XPATH_NAME)
                .write_text_content(BytesText::from_escaped(xpath))?;

            writer.write_event(Event::End(root.to_end()))?;
        } else {
            writer.write_event(Event::Empty(root))?;
        }

        Ok(())
    }
}
impl Transforms {
    pub fn to_xml<W: Write>(&self, writer: &mut Writer<W>) -> Result<(), Box<dyn Error>> {
        let root = BytesStart::new(TRANSFORMS_NAME);
        writer.write_event(Event::Start(root.borrow()))?;
        for transform in &self.transforms {
            transform.to_xml(writer)?;
        }
        writer.write_event(Event::End(root.to_end()))?;
        Ok(())
    }
}
```

**Comment by Weasy666** [comment]
Gotcha. I had just hoped, that there is another way, even if less efficient, to write a string unescaped, so that we can upgrade to a newer quick-xml version without rewriting a significant potion of the code base.
We would change it to the more efficient way in a follow-up attempt.
But if you say that there is now way to do that, then it looks like we need to everything at once.

**Comment by Mingun** [comment]
Well, you can first rewrite, then upgrade, because 0.23 also allows to write in such manner. That way you can upgrade your software by chunk-by-chunk.

Also, I've seen that you used serde. Serde support was significantly improved and now consistent, maybe you could refuse manual serialization. Check out [our documentation](https://docs.rs/quick-xml/latest/quick_xml/de/index.html#table-of-contents) for mapping.
