### ISSUE TITLE
Unable to deserialize `<tag attr="1"/>` in quick-xml 0.27.x

### ISSUE THREAD

**Issue by hds** [tafia/quick-xml#576]
I have found what appears to be a regression, or perhaps just something I'm doing wrong, starting in quick-xml 0.27.

## Affected crate

quick-xml

## Affected version(s)

* 0.27.0
* 0.27.1

## Platform

Result of `uname -a`:

`Linux sync-z2 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

## Description

I have the following test case:

```rust
static BUFFER: &str = r#"<tag attr="1"/>"#;

#[derive(serde::Deserialize)]
pub struct Tag {
    pub attr: u32,
}

#[test]
fn quick_xml() {
    let _mog: Tag = quick_xml::de::from_str(BUFFER).unwrap();
}
```

This **passes in 0.26.0** and prior, but **fails in 0.27.0** (and 0.27.1).

Unfortunately, I haven't been able to determine why from the changes between those two versions.

**Comment by Mingun** [comment]
You should change your definition, because since 0.27.0 attributes explicitly indicated by `@` character in their names:
```rust
#[derive(serde::Deserialize)]
pub struct Tag {
    #[serde(rename = "@attr")]
    pub attr: u32,
}
```
See also [our documentation](https://docs.rs/quick-xml/latest/quick_xml/de/index.html#table-of-contents) for mapping.

**Comment by hds** [comment]
Thank you very much for your quick response.

I thought that it might have been something like that (I mean, there had been some change that I hadn't understood and that I needed to change my model).

If you don't mind answering another enquiry, does this mean that `quick-xml` will now be "round trip" safe, because it's able to distinguish attributes from child tags?

**Comment by Mingun** [comment]
Yes, and we recently [add](https://github.com/tafia/quick-xml/pull/574) tests that ensure this.

**Comment by hds** [comment]
Fantastic. Thank you once again for your quick response! And also sorry for reporting something which is described on the first page of the docs, I don't know how I missed it.
