### ISSUE TITLE
Optional unescaping with serde

### ISSUE THREAD

**Issue by pigeonhands** [tafia/quick-xml#581]
Currently, trying to use `quick_xml::de::from_str` with xml that uses `entity` tags in the doctype fail to parse.

```XML
<!DOCTYPE dict[
    <!ENTITY unc "unclassified">
]>

<dict>
    <word>&unc;</word>
</dict>
```
```rust
let data = fs::read_to_string("../data/dict.xml").unwrap();
let parsed : Dict = quick_xml::de::from_str(&data).unwrap();
```
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidXml(EscapeError(UnrecognizedSymbol(1..4, "unc")))'

------

Could a feature flag or an alternate method be added that disables unescaping and instead always just returns the raw string?

**Comment by pigeonhands** [comment]
@Mingun I'm not really sure how to go about this. I have created a fork that implements a resolver but  its not going to be able to access the entities defined in the document because that parsing is handled outside the `de` module.

https://github.com/pigeonhands/quick-xml/commit/ddacb310a2d50472e50acbf0b0d3113e28a4b60e

**Comment by Mingun** [comment]
Wow! Your implementation looks promising! I think, it would be better if you create a draft PR so we can discuss on actual implementation in context.

You need to capture `DocType` events in this match:
https://github.com/tafia/quick-xml/blob/2e9123a5435683e1b2cffb0de547f972b383bbd3/src/de/mod.rs#L2745-L2765

For that change the `EntityResolver` trait to that (feel free to fix grammar if I made mistakes):
```rust
/// Used to resolve unknown entities while parsing
///
/// # Example
/// Add an example here -- you can adapt existing custom_entities.rs example
pub trait EntityResolver {
    /// Called on contents of [`Event::DocType`] to capture declared entities.
    /// Can be called multiple times, for each parsed doctype declaration.
    fn capture(&mut self, doctype: BytesText);

    /// Called when an entity needs to be resolved.
    ///
    /// `None` is returned if a suitable value can not be found.
    /// In that case an [`Error::UnrecognizedSymbol`] will be returned.
    fn resolve<'entity>(&'entity self, entity: &str) -> Option<&'entity str>;
}
```
`resolve` method no need to be mutable -- it used only for requesting information. If implementation would need mutation in that case it should use internal mutability, using `Cell` or something.
