### ISSUE TITLE
How to deal with duplicate attribute name and node name

### ISSUE THREAD

**Issue by ice-curtain** [tafia/quick-xml#587]
xml:
```xml
<a m="777">
    <m val="hehe"/>
</a>

```
I define a struct like this:
```rust
#[derive(Serialize, Deserialize, Debug)]
pub struct A {
    m: String,

    #[serde(rename="m")]
    mval: OnlyVal,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct OnlyVal {
    val: String,
}
```
And I get :"thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("duplicate field `m`")'"

**Comment by Mingun** [comment]
Read [this](https://docs.rs/quick-xml/latest/quick_xml/de/) documentation. TLDR: rename attribute fields to `@field_name`
