### ISSUE TITLE
Is an XML document valid if there is only an XML declaration?

### ISSUE THREAD

**Issue by j3rrywan9** [tafia/quick-xml#599]
I'm evaluating both `quick-xml` (0.28.2) and `xml-rs` (0.8.5) for my project, and I noticed a different behavior between the two when it comes to parsing an XML document with only an XML declaration:
```rust
fn main() {
    let xml = r#"<?xml version="1.0" encoding="UTF-8"?>"#;
    let mut reader = Reader::from_str(xml);
    reader.trim_text(true);

    let mut buf = Vec::new();

    loop {
        match reader.read_event_into(&mut buf) {
            Err(e) => panic!("Error at position {}: {:?}", reader.buffer_position(), e),
            Ok(Event::Eof) => break,
            _ => (),
        }
        buf.clear();
    }

    let xml_string = String::from(xml);
    let reader = Cursor::new(xml_string);
    let mut parser = EventReader::new(reader);
    loop {
        match parser.next() {
            Err(e) => panic!("{}", e.to_string()),
            Ok(XmlEvent::EndDocument) => break,
            _ => (),
        }
    }
}
```
The first loop works just fine (implemented using `quick-xml`), while the second (implemented using `xml-rs`) panics with as follows:
```
thread 'main' panicked at '1:39 Unexpected end of stream: no root element found'
```
So I'm wondering if an XML document is valid if there is only an XML declaration in it.

**Comment by dralley** [comment]
It's required for XML 1.1 documents, but not XML 1.0 documents, unless the text encoding is something other than UTF-8 or UTF-16.

quick-xml does not enforce this however, it just gives you a stream of XML events to be interpreted however you wish.

**Comment by Mingun** [comment]
XML with only a prolog [is invalid](https://www.w3.org/TR/xml11/#NT-document), but quick-xml does not check validity of documents -- it just streams events. quick-xml could do some checks but all of them are optional for maximal flexibility. I'm fine, however, to accept a PR which will add a new Reader type which will perform checks (or an additional generic parameter for existing `Reader`)
