### ISSUE TITLE
AsyncWrite trait implementation and indentation 

### ISSUE THREAD

**Issue by damb** [tafia/quick-xml#605]
Hi,

in order to create a `Writer<W>` with configured indents `W` is required to implement the `Write` bound. However, if writing events asynchronously, indentation is not supported by the library. Is there a reason why this feature is not implemented? What about providing indentation for `AsyncWrite` trait implementations? What do you think?

**Comment by Mingun** [comment]
There is no specific reason. As was noted in #573, indentation just was not implemented as was not used by original implementer. Feel free to submit PR to add it.

**Comment by damb** [comment]
Ok, thanks for pointing me to #573. I'm going to give it a try.
