### ISSUE TITLE
Debug assertion triggered on empty doctype

### ISSUE THREAD

**Issue by Tpt** [tafia/quick-xml#608]
Thank you for quick-xml and sorry for comming back with an other bug.

When parsing the file `<!DoctyPE>` using rusc "dev" profile the assertion `"DocType must have a name"` is triggered. In the "release" profile the assertion is not triggered and the parser returns an empty `Event::Doctype()`

Test failing in "dev" profile and passing in "release" profile:
```rust
#[test]
fn reproduce() {
    let data = b"<!DoctyPE>";
    let mut reader = Reader::from_reader(data.as_slice());
    let mut buf = Vec::new();
    loop {
        match reader.read_event_into(&mut buf) {
            Ok(Event::Eof) => break,
            Ok(Event::DocType(e)) => assert!(e.is_empty()), // assertion only executed in "release" mode
            _ => unreachable!()
        }
    }
}
```

**Comment by Mingun** [comment]
Yes, I think, we should either to parse this correctly into an event or return a normal error if this violates XML rules

**Comment by Tpt** [comment]
[XML 1.0 grammar](https://www.w3.org/TR/xml/#NT-doctypedecl) seems to require at least one "Name" into the Doctype declaration. So, this case seems to violate XML rules.
