### ISSUE TITLE
Order of repeating elements

### ISSUE THREAD

**Issue by unshakable-horse** [tafia/quick-xml#614]
I have a piece of xml like below:
```xml
<p name="foo">
    <age>31<age>
    
    <m>...<m>
    <n>...<n>
    <m>....<m>
    <m>....<m>
    <n>...<n>
</p>
```
I designed a structure as follows：
```rust
pub struct P{
    #[serde(rename="@name")]
    name:String,
    age:i32,
    
    m:Vec<String>,
    n:Vec<String>
}
```

It works fine while deserializing, but when I re-serialize it, the m elements and n elements are not in the original order anymore.
like this:
```xml
<p name="foo">
    <age>31</age>
    <m>...</m>
    <m>...</m>
    <m>...</m>
    <n>...</n>
    <n>...</n>
    <n>...</n>
</p>
```

Is there any way to get it back to the correct order ？

**Comment by unshakable-horse** [comment]
It works fine when the repeating element is a string, but if it is a struct, an error occurs:"struct `M` cannot be serialized as an attribute or text content value".
xml is as follows:
```xml
<p name="foo">
    <age>31</age>

    <m>
        <catname>cat1</catname>
    </m>
    <n>
        <dogage>7</dogage>
    </n>
    <m>
        <catname>cat2</catname>
    </m>
    <m>
        <catname>cat3</catname>
    </m>
    <n>
        <dogage>7</dogage>
    </n>
</p>
```

**Comment by Mingun** [comment]
Because everything work as expected I going to close the issue. Feel free to ask additional questions if something is unclear.
