### ISSUE TITLE
Provision for application errors in `ElementWriter::write_inner_content`

### ISSUE THREAD

**Issue by harmic** [tafia/quick-xml#619]
`write_inner_content` is defined like this:

```rust
pub fn write_inner_content<F>(self, closure: F) -> Result<&'a mut Writer<W>>
where
    F: FnOnce(&mut Writer<W>) -> Result<()>,
```

This means that the `closure` can only return errors defined by quick_xml.

At present there doesn't seem to be any option within `quick_xml::Error` for wrapping an application generated error, so my options are limited if I want to bubble up some internal error.

One solution would be to provide another error variant, `CustomError<dyn Box<std::error::Error>>`, and ideally also provide a `From` implementation along with it so that `?` can do its magic.

**Comment by Mingun** [comment]
I think, that we generally need to review our `Error` and `DeError` types because they looks random and inconsistent. It will be good to address this issue during that redesign.
