### ISSUE TITLE
Documentation On How to Iterate Through a Series of XML Elements and Make Objects Out of Those Elements.

### ISSUE THREAD

**Issue by AlexCreamer** [tafia/quick-xml#62]
For example, how could I iterate through the following xml elements and extract each text: 
```<tag1>text1</tag1><tag1>text2</tag1><tag1>text3</tag1><tag1><tag2>text4</tag2></tag1> ```

**Comment by tafia** [comment]
Sorry for the late answer!
Here is a typical implementation, using the example on readme:

```rust
use quick_xml::reader::Reader
use quick_xml::events::Event;

let xml = "<tag1>text1</tag1><tag1>text2</tag1><tag1>text3</tag1><tag1><tag2>text4</tag2></tag1>";

let mut reader = Reader::from_str(xml);
reader.trim_text(true);

let mut txt = Vec::new();
let mut buf = Vec::new();

loop {
    match reader.read_event(&mut buf) {
        Ok(Event::Text(e)) => txt.push(e.unescape_and_decode(&reader).expect("Cannot decode text value")),
        Ok(Event::Eof) => break, // exits the loop when reaching end of file
        Err(e) => panic!("Error at position {}: {:?}", reader.buffer_position(), e),
        _ => (), // There are several other `Event`s we do not consider here
    }
    buf.clear();
}

println!("{:?}", txt);
```

**Comment by AlexCreamer** [comment]
How could I do txt.push just on an instance when a certain xml tag was reached (e.g., tag2)? The reason for asking is because I want to specific information from a website and I assume using parse would be the best way.

**Comment by tafia** [comment]
I guess you want to use the `name` function:
```rust 
Ok(Event::Text(e)) if e.name() == b"tag2" =>
...
```

**Comment by AlexCreamer** [comment]
I tried adding to the following, https://is.gd/3JlCqT, and I get an error saying:
error: no method named `name` found for type `quick_xml::events::BytesText<'_>` in the current scope
  --> src/main.rs:18:37
   |
18 |             Ok(Event::Text(e)) if e.name() == b"tag2" => {
   |                                     ^^^^

error: aborting due to previous error

error: Could not compile `quickxml`.

**Comment by tafia** [comment]
Sorry my bad!! The `name` function is for `BytesStart` structs.
I've pushed the example is the repo:
https://github.com/tafia/quick-xml/blob/master/examples/read_texts.rs

**Comment by tafia** [comment]
@AlexCreamer is the example ok? Can we close that issue?

**Comment by AlexCreamer** [comment]
I'll probably have some more questions but feel free to close the issue.
