### ISSUE TITLE
feat: `const` constructor for `LocalName`

### ISSUE THREAD

**Issue by WhyNotHugo** [tafia/quick-xml#621]
## Feature request

This is a feature request for some mechanism to define a `LocalName` instance
in a `const` context.

## Context

I have a lot of code that looks like this:

```rust
match reader.read_resolved_event_into(buf)? {
    (ResolveResult::Bound(NS_DAV), Event::Start(element))
        if element.local_name().as_ref() == b"href" =>
    {
```

The `if` there really makes matches hard to read, since the condition ends up
always taking multiple lines.

I'd like to somehow define some constants, e.g.:

```rust
const HREF: LocalName = ...
```

So that I can write more "normal" match rules:

```rust
match reader.read_resolved_event_into(buf)? {
    (ResolveResult::Bound(NS_DAV), Event::Start(HREF)) => {
```

Aside from being a bit more readable, they should be a wee bit more performant
too.

**Comment by WhyNotHugo** [comment]
Note that this is possible from within the `quick_xml` crate via:

```rust
const HREF : LocalName = LocalName(b"href");
```

However this is not possible in the scope of a consumer because the inner attribute is private (and rightfully so).

**Comment by WhyNotHugo** [comment]
It's possible to create a `QName` with bogus data and then create a `LocalName` from it, so I guess that the `LocalName` type is not very strict right now.

I wonder if such a constructor should be a validating one or just allow any array of bytes.

**Comment by WhyNotHugo** [comment]
My assumptions here were wrong, and this won't work out as intended. Closing.

**Comment by Mingun** [comment]
Actually, I would happy to make some `QName` API `const`, so you could write
```rust
const local: LocalName = QName(b"myname").local_name();
```
`LocalName` is intentionally opaque type. I would like to keep it so

**Comment by WhyNotHugo** [comment]
I realised that this won't work for a `match` statement (as in the above scenario).

In this snippet (same as above):

```rs
match reader.read_resolved_event_into(buf)? {
    (ResolveResult::Bound(NS_DAV), Event::Start(element))
        if element.local_name().as_ref() == b"href" =>
    {
``` 

`element` is a `QName` but it contains the unqualified namespace, so it can be something like `ns0:href`, `D:href`, etc.
