### ISSUE TITLE
patch vs. minor version bumps

### ISSUE THREAD

**Issue by cmyr** [tafia/quick-xml#626]
I just noticed that v0.30.0 was published, and this raised a question for me:

Before version 1.0, a minor version bump is a breaking change. From a quick glance, it does not appear that there were any actually breaking changes in the code between 0.29 and 0.30. Before 1.0, [semver guarantees are very loose](https://semver.org/#spec-item-9). My personal feeling is that before 1.0, the patch field should be used for any non-breaking changes; the main benefit of this is that it lets cargo continue to resolve disparate dependency versions automatically.

Concretely, the current practice is a bit of a headache for me because I have a number of crates that rely on both the `plist` crate (which relies on `quick_xml`) as well as on `quick_xml` directly. This makes it easy for me to end up in the situation where I am compiling two different versions of `quick_xml` unnecessarily.

For further discussion of the semantic meaning of the minor/patch versions before 1.0, I found [this discussion helpful](https://github.com/semver/semver/issues/333).

(If it turns out that there was actually some breaking change that I didn't notice then please accept my apologies and close this 😁)

**Comment by dralley** [comment]
I don't have especially strong opinions, so if bumping the y-versions leads to real practical issues for a significant group of people, then I suppose I am neutral towards using z-releases instead.   Mostly because we have pretty good test coverage, though.

**Comment by dralley** [comment]
It helps that the changes have been smaller lately, too.  A few months ago we were still merging multiple large (hundreds of lines each) PRs per release, and changes of that magnitude feel minor-bump-worthy even if they don't obviously break anything.

But that's not currently the case.

**Comment by cmyr** [comment]
This discussion has prompted me to wonder whether it's worth considering 1.0 soon? Opened #627 for that discussion.
