### ISSUE TITLE
String returned instead of &str

### ISSUE THREAD

**Issue by dev-ardi** [tafia/quick-xml#648]
Sometimes when the text has weird stuff in it:

```xml
attrib="redacted&#10;&#10;redacted&#10;&#10;redacted&#10;"
```
fails for 
```rs
    #[serde(rename = "@attrib")]
    pub meaning: Option<&'a str>,
```
with 

`Custom("invalid type: string \"redacted", expected a borrowed string")`

**Comment by Mingun** [comment]
[This is by design](https://www.w3.org/TR/xml11/#AVNormalize). Entities and character references should be expanded, so we need to allocate new string and as a result cannot store it to a field, that borrow it's content from the input.
