### ISSUE TITLE
Improve docs on `Reader#read_event()`, `BytesText#decode` and buf arguments

### ISSUE THREAD

**Issue by Enet4** [tafia/quick-xml#66]
I was recently stuck on an issue when migrating one of my tools to quick-xml. The problem was that the parser accumulates bytes read into the given buffer, and the method `BytesText#unescape_and_decode` was simply grabbing everything in the buffer into a String, which included previously read content that was not even part of the text segment. Apparently this means that users of this API _must_ clear the buffer before reading the next event. This isn't unintuitive at the moment.

Is there something I'm missing that should be included in the documentation? Besides, what is the purpose of this `buf` argument? Couldn't reader objects simply own the buffer?

**Comment by tafia** [comment]
Thanks for opening the issue.

>  the method BytesText#unescape_and_decode was simply grabbing everything in the buffer into a String, which included previously read content that was not even part of the text segment.

This looks like a bug, the `BytesText` slice start is [initialized at the end of the buffer before parsing](https://github.com/tafia/quick-xml/blob/master/src/reader.rs#L151).
Could you provide me with a broken test?

> Besides, what is the purpose of this buf argument? Couldn't reader objects simply own the buffer?

Having control over the internal buffer provides several benefit at the little cost of moving that buffer around:
- in most cases, you do not want to return the content of all events, only the texts after some rare start events. You do not want to allocate a new buffer every single time.
- on the other hand, you may want to reserve the buffer once for all (you know the size of the file for instance). Just set the buffer capacity before parsing!
- the events are, as much as possible, using `Cow` ... which means there is no extra allocation. The includes the `unescape` and the `decode` parts!

Let me know if I am not clear.

**Comment by Enet4** [comment]
Thanks for the reply. I did not exclude the chance of facing a bug, but I wished to make sure that it wasn't just a misunderstanding of the API.

I managed to fix the tool shortly before posting this issue, the code is in one of my repos [here](https://github.com/Enet4/dicom-rs/blob/31820e8768eecb39eaa14f56d7d545d9f2eec41e/dictionary_builder/main.rs). In a single line, this tool parses a part of the DICOM standard to retrieve a list of attributes, yielding an iterator that can then be used to generate code or other data structures. It's possibly not the most elegant way to achieve this, but it works as intended and runs faster than ever. The bug occurs when [line 174](https://github.com/Enet4/dicom-rs/blob/31820e8768eecb39eaa14f56d7d545d9f2eec41e/dictionary_builder/main.rs#L174) is removed. I'm afraid that this is all I have to reproduce the issue right now.

**Comment by tafia** [comment]
@Enet4 thank you for the issue. It was definitely a bug. I am very sorry for the time you've spent on this.
I could catch it in my tests too if I force not clearing the buffer.

Should be fixed in #67. Let me know.

(I think you should keep the `buffer.clear()` for performance reasons).

Published version 0.7.3

**Comment by Enet4** [comment]
Yes, the fix worked! Good job and thanks for the help. :+1:
