### ISSUE TITLE
xml serde read translates optional attributes with value "" to None

### ISSUE THREAD

**Issue by francisdb** [tafia/quick-xml#671]
If you want to be able to make a difference between attribute missing and attribute empty `""` should serialize to `Some("")` but those attributes deserialize to `None`.
(useful for roundtrips where the output should be equal to input with small change applied)

```rust
use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize, PartialEq, Eq)]
struct Name {
    #[serde(rename = "@first_name", skip_serializing_if = "Option::is_none")]
    first_name: Option<String>,
    #[serde(rename = "@second_name", skip_serializing_if = "Option::is_none")]
    second_name: Option<String>,
}

#[test]
fn read_and_write() {
    let expected = Name {
        first_name: Some("aaa".to_string()),
        second_name: Some("".to_string()),
    };

    let name =
        quick_xml::de::from_str::<Name>(r#"<Name first_name="aaa" second_name=""/>"#).unwrap();

    assert_eq!(expected, name);

    let s = quick_xml::se::to_string(&name).unwrap();

    assert_eq!(r#"<Name first_name="aaa" second_name=""/>"#, s);
}
```

fails with

```
thread 'read_and_write' panicked at tests/tezt.rs:21:5:
assertion `left == right` failed
  left: Name { first_name: Some("aaa"), second_name: Some("") }
 right: Name { first_name: Some("aaa"), second_name: None }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I found similar issues that are marked as fixed: #252 and #527

**Comment by Mingun** [comment]
Yes, the problem only on Deserializer side, it is not tested in [tests](https://github.com/tafia/quick-xml/blob/27a93b3259be5ab74387a725386cd9226128ab06/tests/serde-issues.rs#L17-L49) for #252. Probably should be an easy fix.

**Comment by francisdb** [comment]
If you want I can have a look at a PR this evening, however I see you self-assigned this?

**Comment by Mingun** [comment]
I'd looked at this. The current behavior was selected to match `serde_json` behavior which translates `{ "a": null }` to `a: None`. In XML the closest analogues to `null` is empty value of attribute. But maybe we need to review this again.

**Comment by francisdb** [comment]
Json `{ "a": "" }` will probably give you `a: Some("")` which is similar to what this issue is going for?

The tricky part is that for json both `{ "a": null }` and `{}` will return `a: None` so its impossible to do a round trip keeping exact equal representation. For xml there is no such issue.

**Comment by francisdb** [comment]
Great, thanks @Mingun
I see a `0.31.0` release was made but it seems to be missing on crates.io?
https://crates.io/crates/quick-xml
