### ISSUE TITLE
`xmlns:ns` is now returned as attribute

### ISSUE THREAD

**Issue by torokati44** [tafia/quick-xml#676]
We're seeing a change of behavior starting with https://github.com/tafia/quick-xml/pull/545.

This causes CI on https://github.com/ruffle-rs/ruffle/pull/13785 to fail: https://github.com/ruffle-rs/ruffle/actions/runs/6709470764/job/18232602777

The specific code that's broken:
```actionscript
var y1 = <y xmlns:ns="foo" a="10" ns:c="30" ns:d="40"/>;
trace(y1.@*);
```

Expected: `103040`
Ruffle with quick-xml update: `foo103040`

It seems the `xmlns:ns` attribute is now returned when it previously wasn't.
Is this expected? If so, could you assist us in how to get back the old behavior?

**Comment by Mingun** [comment]
Could you explain, what that syntax mean and should do?
```actionscript
var y1 = <y xmlns:ns="foo" a="10" ns:c="30" ns:d="40"/>;
trace(y1.@*);
```

**Comment by torokati44** [comment]
Yes, sorry, this was not evident at all... 😅

This is ActionScript - the programming language for Adobe Flash movies.

This test is supposed to list all the attribute values of the element.
An excerpt from the documentation:

> You can use the * wildcard symbol with the @ symbol to access all attributes of an XML or XMLList object, as in the following code:

```
var employee:XML =  
    <employee id="6401" code="233"> 
        <lastName>Wu</lastName> 
        <firstName>Erin</firstName> 
    </employee>; 
trace(employee.@*.toXMLString());  
// 6401 
// 233
```

https://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118a9b90204-7e6b.html#WS5b3ccc516d4fbf351e63e3d118a9b90204-7e61

**Comment by torokati44** [comment]
As for how `quick-xml` is used, I think this is a good place to start looking around: https://github.com/ruffle-rs/ruffle/blob/36eda351972d903711dc910d5c07b4f8fe974347/core/src/avm2/e4x.rs#L7

**Comment by Dinnerbone** [comment]
I looked into this on the Ruffle side, it's our mistake, sorry!

We expected to see `xmlns` and `xml` as `ResolveResult::Unknown("xmlns")`/`ResolveResult::Unknown("xml")` - so the change to resolve them out to their URLs threw us off.

**Comment by torokati44** [comment]
Turns out, this was on us. Sorry for bothering you and wasting your bandwidth... :disappointed:
