### ISSUE TITLE
Lists can be serialized but the result can not be deserialized

### ISSUE THREAD

**Issue by GunnarMorrigan** [tafia/quick-xml#682]
quickl xml is not able to deserialize an empty vector. Example below panics at the deserializing of the serialized struct

```rust
use serde;
use quick_xml;

#[derive(serde::Serialize, serde::Deserialize)]
struct Elements {
    #[serde(rename = "list")]
    elems: Vec<()>,
}

fn main() {
    let a = Elements {
        elems: vec![],
    };
    let mut res_string = quick_xml::se::to_string(&a).unwrap();

    res_string = dbg!(res_string);

    let r_2: Result<Elements, quick_xml::DeError> = quick_xml::de::from_str(&res_string);

    assert!(r_2.is_ok()); // <- panics
}
```

While this does work:

```rust
fn main() {
    let a = Elements {
        elems: vec![()],
    };
    let mut res_string = quick_xml::se::to_string(&a).unwrap();

    res_string = dbg!(res_string);

    let r_2: Result<Elements, quick_xml::DeError> = quick_xml::de::from_str(&res_string);

    assert!(r_2.is_ok());
}
```

I think the notion of a vector is that it could also be empty? and thus not contain any elements

**Comment by GunnarMorrigan** [comment]
This can be solved by using default tag in serde 

```
#[serde(rename = "list", default)]
    elems: Vec<()>,
```

but I am not sure if this is the proper solution

**Comment by Mingun** [comment]
This is a proper solution. You also can wrap your `Vec` into `Option` if that makes sense. The problem is in XML format itself which has no dedicated syntax for arrays -- an empty array is indistinguishable from the complete absence of a field, and serde is sharpened just for the last case.

**Comment by GunnarMorrigan** [comment]
Hi @Mingun,

I tried wrapping in Option but this also did not work.

**Comment by Mingun** [comment]
Yes, when use `Option`, the field itself is serialized and the whole result is
```xml
<Elements><list/></Elements>
```
You also need to apply `#[serde(skip_serializing_if = "Option::is_none")]` to the field in that case to serialize to
```xml
<Elements/>
```
Then roundtrip is working:
```rust
#[test]
fn issue682_option() {
    #[derive(Serialize, Deserialize, Debug, PartialEq)]
    struct Elements {
        #[serde(rename = "list", skip_serializing_if = "Option::is_none")]
        elems: Option<Vec<()>>,
    }

    let a = Elements {
        elems: None,
    };
    let res_string = dbg!(to_string(&a).unwrap());
    assert_eq!(from_str::<Elements>(&res_string).unwrap(), a);
}
```
Such asymmetry is a compromise in XML, because it does not have a dedicated syntax for sequences.
