### ISSUE TITLE
Trying to serialize untagged enum brings "serialization of struct `SubResponseType` is not supported in `$value` field"

### ISSUE THREAD

**Issue by lyssieth** [tafia/quick-xml#688]
I have an enum that contains different types of response (`SubResponseType`), and it has to be `#[serde(untagged)]` because otherwise the Json alternative complains (specifically because of flattening enums. The API is weird, but I have to support its weirdness.)

This is only ever _serialized_, and never deserialized.

A simple reproduction would be something like https://gist.github.com/lyssieth/ab7bc6f5836d259c467667bc01dbd743

**Comment by Mingun** [comment]
Could you explain, what output is expected for each variant?

**Comment by lyssieth** [comment]
Actually I think I've been implementing it wrongly on my end... apologies.
