### ISSUE TITLE
provide trace if parsing fails

### ISSUE THREAD

**Issue by Thomblin** [tafia/quick-xml#697]
In my opinion it is quite difficult to find errors in my Rust types (structs) if parsing a larger XML fails. I figured out that `serde_path_to_error` is a very helpful crate to improve the error message by at least providing a path (trace) related to the rust type that is failing. 

This small snippet is good enough to provide that feature. I use almost the same structure as `pub fn from_str<'de, T>(s: &'de str) -> Result<T, DeError>`

```rust
use quick_xml::DeError;
use serde::Deserialize;
use serde_path_to_error::{Deserializer, Track};

pub fn from_str_tracked<'de, T>(s: &'de str) -> Result<T, (DeError, String)>
where
    T: Deserialize<'de>,
{
    let de = &mut quick_xml::de::Deserializer::from_str(s);

    let mut track = Track::new();
    let pd = Deserializer::new(de, &mut track);

    match T::deserialize(pd) {
        Ok(res) => Ok(res),
        Err(e) => {
            let path = track.path().to_string();
            Err((e, path))
        }
    }
}
```

My question is: Is it worth to be provided in the quick_xml::de docs or even as a new function (bound to a feature serialize-track for example)?

**Comment by Mingun** [comment]
Providing a location of error is tracked in #313. I do not think, that new feature is needed (there are many crates in the ecosystem, we do not need to provide a feature for each of them), but mention in the documentation is possible. You can make a PR.
