### ISSUE TITLE
Error "Unexpected Event::Start" when deserializing enum with struct variants

### ISSUE THREAD

**Issue by luca-della-vedova** [tafia/quick-xml#699]
Hello and thanks for the great crate!

I'm trying to parse an enum with a struct variant that has only attributes but I keep getting errors about an unexpected start event, minimum reproducible example:

```rust
use quick_xml::de::from_str;
use serde::Deserialize;

#[derive(Debug, Deserialize, Clone)]
#[serde(rename_all = "snake_case")]
pub enum Geometry {
    Cube {
        #[serde(rename = "@size")]
        size: f64,
    },
}

#[derive(Debug, Deserialize, Clone)]
#[serde(rename = "object")]
pub struct Object {
    geometry: Geometry,
}

const XML: &str = r#"
<?xml version="1.0" encoding="utf-8"?>
<object>
  <geometry>
    <cube size="3.3" />
  </geometry>
</object>
"#;

fn main() {
    let o: Object = from_str(XML).map_err(|e| e.to_string()).unwrap();
}
```

This outputs:

```
thread 'main' panicked at examples/read_nodes_serde.rs:33:62:
called `Result::unwrap()` on an `Err` value: "Unexpected `Event::Start(\"cube\")`"
```

Which I found puzzling, I tried for curiosity to remove the `cube` element from the input xml to see what the parser was expecting and the error changed into:

```
thread 'main' panicked at examples/read_nodes_serde.rs:32:62:
called `Result::unwrap()` on an `Err` value: "unknown variant `$text`, expected `cube`"
```

Which makes me think that it is indeed expecting a `cube`?
Am I doing something wrong or should this not be the case?

**Comment by Mingun** [comment]
You need to use intermediate struct for `geometry` field. Just imagine where you should store attributes that could appear in `<geometry>` tag. See also the second row [here](https://docs.rs/quick-xml/latest/quick_xml/de/index.html#choices-xschoice-xml-schema-type).

[The fixed example](https://www.rustexplorer.com/b#LyoKW2RlcGVuZGVuY2llc10KcXVpY2steG1sID0geyB2ZXJzaW9uID0gIjAuMzEiLCBmZWF0dXJlcyA9IFsic2VyaWFsaXplIl0gfQpzZXJkZSA9IHsgdmVyc2lvbiA9ICIxLjAiLCBmZWF0dXJlcyA9IFsiZGVyaXZlIl0gfQoqLwp1c2UgcXVpY2tfeG1sOjpkZTo6ZnJvbV9zdHI7CnVzZSBzZXJkZTo6RGVzZXJpYWxpemU7CgojW2Rlcml2ZShEZWJ1ZywgRGVzZXJpYWxpemUsIFBhcnRpYWxFcSldCiNbc2VyZGUocmVuYW1lX2FsbCA9ICJzbmFrZV9jYXNlIildCnB1YiBlbnVtIEdlb21ldHJ5IHsKICAgIEN1YmUgewogICAgICAgICNbc2VyZGUocmVuYW1lID0gIkBzaXplIildCiAgICAgICAgc2l6ZTogZjY0LAogICAgfSwKfQoKI1tkZXJpdmUoRGVidWcsIERlc2VyaWFsaXplLCBQYXJ0aWFsRXEpXQpwdWIgc3RydWN0IEdlb21ldHJ5VGFnIHsKICAgICNbc2VyZGUocmVuYW1lID0gIiR2YWx1ZSIpXQogICAgdmFsdWU6IEdlb21ldHJ5LAp9CgojW2Rlcml2ZShEZWJ1ZywgRGVzZXJpYWxpemUsIFBhcnRpYWxFcSldCnB1YiBzdHJ1Y3QgT2JqZWN0IHsKICAgIGdlb21ldHJ5OiBHZW9tZXRyeVRhZywKfQoKY29uc3QgWE1MOiAmc3RyID0gciMiCjw/eG1sIHZlcnNpb249IjEuMCIgZW5jb2Rpbmc9InV0Zi04Ij8+CjxvYmplY3Q+CiAgPGdlb21ldHJ5PgogICAgPGN1YmUgc2l6ZT0iMy4zIiAvPgogIDwvZ2VvbWV0cnk+Cjwvb2JqZWN0PgoiIzsKCmZuIG1haW4oKSB7CiAgICBsZXQgbzogT2JqZWN0ID0gZnJvbV9zdHIoWE1MKS5tYXBfZXJyKHxlfCBlLnRvX3N0cmluZygpKS51bndyYXAoKTsKICAgIHByaW50bG4hKCJ7OiM/fSIsICZvKTsKICAgIGFzc2VydF9lcSEoCiAgICAgICAgbywKICAgICAgICBPYmplY3QgewogICAgICAgICAgICBnZW9tZXRyeTogR2VvbWV0cnlUYWcgewogICAgICAgICAgICAgICAgdmFsdWU6IEdlb21ldHJ5OjpDdWJlIHsgc2l6ZTogMy4zIH0sCiAgICAgICAgICAgIH0sCiAgICAgICAgfQogICAgKTsKfQ==).

**Comment by luca-della-vedova** [comment]
I see, thanks a lot for your quick reply!
