### ISSUE TITLE
Question: Element body

### ISSUE THREAD

**Issue by filcuc** [tafia/quick-xml#70]
This is more a question than an issue:
Given an Event for the start of an element how can i obtained all the element body from its start to its end?

**Comment by tafia** [comment]
Do you mean a string extraction of all the sub-elements? 

- Having the text representation is not available out of the box. You should be able to simulate it using both the reader and the writer together. 
- If you just want the list of events, then a simple depth variable is enough (like what is done [here](https://github.com/tafia/quick-xml/blob/master/src/reader.rs#L567-L587) )

**Comment by tafia** [comment]
Closing the issue. Feel free to reopen it if you think the answer is not satisfying.
