### ISSUE TITLE
Ergonomics on a double borrow 

### ISSUE THREAD

**Issue by ncgl-git** [tafia/quick-xml#701]
Even though I'm new to rust, this seems valuable enough to warrant an issue-question.

I started looking at https://capnfabs.net/posts/parsing-huge-xml-quickxml-rust-serde/, to try to chunk large xmls  but for non serialization purposes, when I'm just trying to read elements into a buffer, the below code seems really straight forward and desirable, but the borrow checker prevents it from happening.

Pardon the possible syntax errors, focusing on the 2 &mut buf_chunks in either implementation. Is there a better pattern to allow this approach instead of below?

either

```rust
loop {
  match reader.read_event_into(&mut buf_chunk) {
    Event::Start(event) => reader.read_to_end_into(&mut buf_chunk),
    Event::Eof => break,
    _ => {}
}
```

or 

```rust
fn recurse_chunk<R: BufRead>(reader, buf_chunk) {
  match reader.read_event_into(&mut buf_chunk) {
    Event::Start(e)) => {
      reader.read_to_end_into(e.to_end().name(), &mut buf_chunk),
      recurse_chunk(reader, buf_chunk)
    _ => {}
}
```

EDIT:

for added context, the use case would be chunking a large file (so imagine the match containing logic for counting etc), without having to serialize to a struct.

**Comment by Mingun** [comment]
@ncgl-git, if you found the answer, could you share it here (even if it just "it just works") so if others will face with the same problem they understood why you closed this issue.
