### ISSUE TITLE
Cannot deserialize list of namespaced `xs:choice`

### ISSUE THREAD

**Issue by leftmostcat** [tafia/quick-xml#703]
I have the following XML structure which I wish to deserialize:

```xml
<m:GetFolderResponseMessage ResponseClass="Success">
  <m:ResponseCode>NoError</m:ResponseCode>
  <m:Folders>
    <t:Folder>
      ...
    </t:Folder>
  </m:Folders>
</m:GetFolderResponseMessage>
```

I have tried several possible variations to find a struct which allows this, but none have worked. The following are the common structures in the examples I'm providing:

```rs
#[derive(Debug, Deserialize)]
pub enum Folder {
    CalendarFolder(FolderInner),
    ContactsFolder(FolderInner),
    Folder(FolderInner),
    SearchFolder(FolderInner),
    TasksFolder(FolderInner),
}

#[derive(Debug, Deserialize)]
pub struct FolderInner {
    ...
}

#[derive(Debug, Deserialize)]
pub enum ResponseClass {
    ...
}
```

The following structures cause an error "missing field `$value`":

```rs
#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct GetFolderResponseMessage {
    #[serde(rename = "@ResponseClass")]
    pub response_class: ResponseClass,
    pub folders: Folders,
}

#[derive(Debug, Deserialize)]
pub struct Folders {
    #[serde(rename = "$value")]
    pub inner: Vec<Folder>,
}
```

Both of the following examples result in "unknown variant `Folders`, expected one of `CalendarFolder`, `ContactsFolder`, `Folder`, `SearchFolder`, `TasksFolder`":

```rs
#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct GetFolderResponseMessage {
    #[serde(rename = "@ResponseClass")]
    pub response_class: ResponseClass,
    pub folders: Folders,
}

#[derive(Debug, Deserialize)]
pub struct Folders(Vec<Folder>);
```

```rs
#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct GetFolderResponseMessage {
    #[serde(rename = "@ResponseClass")]
    pub response_class: ResponseClass,
    pub folders: Vec<Folder>,
}
```

**Comment by Mingun** [comment]
> The following structures cause an error "missing field `$value`":

Are you sure that deserialized XML have at least one child in `<Folders>` tag? Because if it is empty, then serde code will not try to atteppt to deserialize anything and we will not have any chance to fill `$value` field. Usually you should either to add `#[serde(default)]` to all `Vec` fields, or wrap them in `Option`.

> Both of the following examples result in "unknown variant `Folders`, expected one of `CalendarFolder`, `ContactsFolder`, `Folder`, `SearchFolder`, `TasksFolder`":

Yes, for that examples this is expected behavior.
