### ISSUE TITLE
Derive Parser fails when elements of the same type are delimited with another element

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [tafia/quick-xml#711]
Assume the following sample XML
```xml
<metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="pub-id">9781975349974</dc:identifier>
    <dc:title>86—EIGHTY-SIX, Vol. 11: Dies Passionis</dc:title>
    <dc:language>en</dc:language>
    <dc:date>2022-11-22</dc:date>
    <dc:creator id="creator01">Asato Asato and Shirabii</dc:creator>
    
    <meta property="role" refines="#creator01">aut</meta>
    <meta property="file-as" refines="#creator01">Shirabii and Asato Asato</meta>
    <meta property="display-seq" refines="#creator01">1</meta>

    <dc:publisher>Yen On</dc:publisher>
    <dc:rights>Copyright © 2022 Asato Asato</dc:rights>
    <meta property="dcterms:modified">2022-11-22T00:00:00Z</meta>
</metadata>
```

When parsing the above XML into the following struct:
```rust
#[derive(Debug, Serialize, Deserialize)]
struct Metadata {
    // Other fields

    #[serde(rename = "meta")]
    meta: Option<Vec<Meta>>,
}
```
with `let reader: Metadata = quick_xml::de::from_str(data).unwrap();` the parser fails with `called 'Result::unwrap()' on an 'Err' value: Custom("duplicate field 'meta'")`. However, when I reorder the XML so that the last `<meta>` element is directly besides the other `<meta>` element, i.e. above the `<dc:publisher>` the parsing completes successfully.

I cannot control the the elements inside the `<metadata>` tag, nor their amount (the EPUB standard states _0:n_ elements). Therefore I need the parser to add the meta tags to the vec regardless of their ordering.

**Comment by 443eb9** [comment]
I also encountered this issue just now. The only difference is that I'm using serde to deserialize the whole xml into a struct.

**Comment by Mingun** [comment]
You need to enable [overlapped-lists](https://docs.rs/quick-xml/latest/quick_xml/#overlapped-lists) feature.

**Comment by Ruhrpottpatriot** [comment]
The overlapped-list feature works.  However, the error message is a bit cryptic. Maybe improve the error so that it points to the feature ?

**Comment by Mingun** [comment]
Unfortunately it is from [derived] implementation of `Deserialize` of the deserialized type. It is format-agnostic, so cannot mention quick-xml specific features.

**Comment by Ruhrpottpatriot** [comment]
Sad to hear that.
Another small question: How do I write XML attribute tags when I don't want/can't use struct attributes? I tried looking into the serializer, but found nothing.

**Comment by Mingun** [comment]
Not exactly understand what you need. To map attribute to a serde model [prepend a `@`](https://docs.rs/quick-xml/latest/quick_xml/de/index.html#basics) to its name. Or use [`with_attribute`](https://docs.rs/quick-xml/latest/quick_xml/writer/struct.ElementWriter.html#method.with_attribute) if you looking for a solution without serde.

**Comment by Ruhrpottpatriot** [comment]
Assume I have this user facing struct:
```
#[derive(Debug)
pub struct Creator {
    pub first_name: String,
    pub last_name: String,
    pub role: String,
    id: String,
}
```
The epub standard doesn't expose these fields in a single tag and you have to split this up into multiple tags. By those requirements the resulting XML looks like this:
```
<metadata>
    <dc:creator id="creator01">first_name last_name</dc:creator>
    <meta refines="creator01"property="role" >aut</meta>
</metadata>
```

Now, the `<metadata>` envelope is not the problem. I want to implement the serialize trait as shown in the [serde documentation](https://serde.rs/impl-serialize.html).
As you can see I need to concat the first and last name (not a problem) into a single field and then create two tags and set the `id` and `refines` attribute to the `id` field of the `Creator` struct. 
With the writer I can do
```
let mut buffer = Vec::new();
let mut writer = Writer::new_with_indent(&mut buffer, b' ', 4);

 let w = writer
    .create_element("dc:creator")
    .with_attribute(("id", "creator01"))
    .write_text_content(BytesText::new("Asato Asato and Shirabii"))
    .unwrap()
    .create_element("meta")
    .with_attribute(("property", "role"))
    .with_attribute(("refines", "#creator01"))
    .write_text_content(BytesText::new("aut"))
    .unwrap();
let s = std::str::from_utf8(&buffer).unwrap();
```
but I can't use this inside the serialize function, right?

**Comment by Mingun** [comment]
Right. The usual approach to made this in serde is to create manual `Serialize` implementation of your struct and internally use the struct with correct shape, that would serialized. Then convert you struct to the internal struct and serialize it. Another way is to call `Serializer` methods manually, but that easy can out of control in case of big structures.

**Comment by Ruhrpottpatriot** [comment]
So basically do this? 
```
impl Serialize for Title {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        #[derive(Debug, Serialize, Deserialize)]
        #[serde(rename = "dc:title")]
        struct RawTitle {
            #[serde(rename = "@id", skip_serializing_if = "Option::is_none")]
            id: Option<String>,

            #[serde(rename = "$value")]
            value: String,

            #[serde(rename = "@lang", skip_serializing_if = "Option::is_none")]
            lang: Option<String>,
        }
    
        let raw_title = RawTitle {
            id: self.id.clone(),
            value: self.value.clone(),
            lang: self.language.clone(),
        };

        raw_title.serialize(serializer)
    }
}
```
It's from another part of the code where I did this already. But I was looking for a way to do this without resorting to having too many additional types that basically just add boilerplate code.

**Comment by Mingun** [comment]
Yes (just note, that you don't need to derive `Deserialize` in that case because it is internal type in `serialize` method and `Deserialize` implementation would not be used anyway).

As I say before, you still can call serde API directly, but in you original case you anyway need to some intermediate types so you can convert a struct into two adjacent tags.

Anyway, this is just general serde questions not tied to quick-xml. You cannot use serializer-specific features in implementation of `Serialize` trait (at least without hacks and `unsafe` code).

If using serde is not a strict requirement, you also can look at [xmlserde](https://github.com/ImJeremyHe/xmlserde) which uses quick-xml under the hood.
