### ISSUE TITLE
Issue deserializing lists of enums using serde derive

### ISSUE THREAD

**Issue by maddymakesgames** [tafia/quick-xml#712]
I'm trying to parse xml with the structure `<root><string>A</string><string>B</string></root>`.
I've tried to implement this using serde derive macros as its easier to maintain.

The code I've tried is 
```rust
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
#[serde(rename = "root")]
struct Root {
    string: Vec<Enum>,
}

#[derive(Serialize, Deserialize, Debug)]
enum Enum {
    A,
    B,
}

fn main() {
    let xml = r#"<root><string>A</string><string>B</string></root>"#;
    let de = quick_xml::de::from_str::<Root>(xml).unwrap();
}
```

This outputs an error ```unknown variant `string`, expected `A` or `B`"```.
But when I try to serialize a struct with the correct format, it succeeds and the serialized output matches my test string.

Is there something I am missing about the representation of enum lists? Or is this an issue with the derive macros that either needs fixing or requires implementing Deserialize / using deserialize_with.

**Comment by Mingun** [comment]
[You need to use](https://www.rustexplorer.com/b#LyoKW2RlcGVuZGVuY2llc10Kc2VyZGUgPSB7IHZlcnNpb24gPSAiMS4wIiwgZmVhdHVyZXMgPSBbImRlcml2ZSJdIH0KcXVpY2steG1sID0geyB2ZXJzaW9uID0gIjAuMzEiLCBmZWF0dXJlcyA9IFsic2VyaWFsaXplIl0gfQoqLwp1c2Ugc2VyZGU6OntEZXNlcmlhbGl6ZSwgU2VyaWFsaXplfTsKCiNbZGVyaXZlKFNlcmlhbGl6ZSwgRGVzZXJpYWxpemUsIERlYnVnLCBQYXJ0aWFsRXEpXQojW3NlcmRlKHJlbmFtZSA9ICJyb290IildCnN0cnVjdCBSb290IHsKICAgIHN0cmluZzogVmVjPFN0cmluZ0VsZW1lbnQ+LAp9CgojW2Rlcml2ZShTZXJpYWxpemUsIERlc2VyaWFsaXplLCBEZWJ1ZywgUGFydGlhbEVxKV0Kc3RydWN0IFN0cmluZ0VsZW1lbnQgewogICAgI1tzZXJkZShyZW5hbWUgPSAiJHRleHQiKV0KICAgIGNvbnRlbnQ6IEVudW0sCn0KI1tkZXJpdmUoU2VyaWFsaXplLCBEZXNlcmlhbGl6ZSwgRGVidWcsIFBhcnRpYWxFcSldCmVudW0gRW51bSB7CiAgICBBLAogICAgQiwKfQoKZm4gbWFpbigpIHsKICAgIGxldCB4bWwgPSByIyI8cm9vdD48c3RyaW5nPkE8L3N0cmluZz48c3RyaW5nPkI8L3N0cmluZz48L3Jvb3Q+IiM7CiAgICBsZXQgXyA9IGRiZyEocXVpY2tfeG1sOjpkZTo6ZnJvbV9zdHI6OjxSb290Pih4bWwpKS51bndyYXAoKTsKfQ==) intermediate container struct `StringElement` for the `<string>` tag:
```rust
/*
[dependencies]
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.31", features = ["serialize"] }
*/
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, PartialEq)]
#[serde(rename = "root")]
struct Root {
    string: Vec<StringElement>,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
struct StringElement {
    #[serde(rename = "$text")]
    content: Enum,
}
#[derive(Serialize, Deserialize, Debug, PartialEq)]
enum Enum {
    A,
    B,
}

fn main() {
    let xml = r#"<root><string>A</string><string>B</string></root>"#;
    let _ = dbg!(quick_xml::de::from_str::<Root>(xml)).unwrap();
}
```
This is a place where you also can put any attributes if they will exist in `<string>`.

That pattern is documented [here](https://docs.rs/quick-xml/latest/quick_xml/de/index.html#element-lists).
