### ISSUE TITLE
Event::Text seemingly returns only newlines.

### ISSUE THREAD

**Issue by emmalexandria** [tafia/quick-xml#713]
I must admit, I've found this library a bit confusing so I could just be off on how to approach this. I'm trying to parse a Wikipedia dump (with a separate parser), but I first need to grab the content between `<page>` tags to pass to the parser. 

This is what I have so far. 
```rust
fn main() {
    let mut xml_reader = Reader::from_file("./wikisource.xml").unwrap();
    let mut buf = Vec::<u8>::with_capacity(1024);

    let mut in_page = false;
    loop {
        match xml_reader.read_event_into(&mut buf) {
            Ok(Event::Start(e)) => {
                let name = e.name();
                let name = xml_reader.decoder().decode(name.as_ref());

                if name.clone().unwrap().as_ref() == "page" {
                    in_page = true;
                }
            }
            Ok(Event::Text(e)) => {
                if in_page {
                    in_page = false;
                    let escaped = &e.into_inner();
                    let text = xml_reader.decoder().decode(&escaped).unwrap();

                    println!("{:?}", String::from(text))
                }
            }
            Ok(Event::Eof) => break,
            Ok(e) => continue,
            Err(e) => panic!("Error at position {}: {:?}", xml_reader.buffer_position(), e)
        }
    }
}
```

The `println!` in the `Ok(Event::Text(e))` only prints out `"\n    "` repeatedly. Am I misunderstanding the purpose of the event or how to use it, or is there a different way to grab the text between two tags? I did try to use `read_to_end_into()`, but I couldn't understand how one turns the `Range<usize>` into actual text.

**Comment by Mingun** [comment]
If your XML looks like
```xml
<page>
    <tag>...</tag>
    text
<page>
```
then you've get exactly that result which your code does. Just after reading `"\n    "` you reset `in_page` and `text` obviously won't be included in the result.
