### ISSUE TITLE
#[serde(flatten)] not working with deserialization

### ISSUE THREAD

**Issue by meettitan** [tafia/quick-xml#714]
I am trying to factor out some commonly used keys in an xml api I am using, using `#[serde(flatten)]`. When using `#[serde(flatten)]` I am getting 

> Custom("invalid type: map, expected a string")

 I would like to avoid manually flattening struct definitions if possible. Hopefully I am just misunderstanding.

Minimum reproducible example:

```rust
//git rev #88aa477
use quick_xml::de::from_str;
use serde::Deserialize;

#[derive(Debug, Deserialize, PartialEq)]
struct Outer {
    #[serde(flatten)]
    foo: Foo,
    #[serde(flatten)]
    bar: Bar,
}

#[derive(Debug, Deserialize, PartialEq)]
struct OuterFlat {
    a: String,
    b: String,
    c: u32,
    d: u32,
}

#[derive(Debug, Deserialize, PartialEq)]
struct Foo {
    a: String,
    b: String,
}

#[derive(Debug, Deserialize, PartialEq)]
struct Bar {
    c: u32,
    d: u32,
}

const XML: &str = "<Outer><a>foo</a><b>bar</b><c>1</c><d>2</d></Outer>";

#[test]
fn test() {
    let de = from_str::<Outer>(XML);
    let expected = Outer {
        foo: Foo {
            a: "foo".to_string(),
            b: "bar".to_string(),
        },
        bar: Bar {
            c: 1,
            d: 2,
        },
    };
    assert_eq!(expected, de.unwrap()) //Custom("invalid type: map, expected a string")
}

#[test]
fn test_flat() {
    let de = from_str::<OuterFlat>(XML);
    let expected = OuterFlat {
        a: "foo".to_string(),
        b: "bar".to_string(),
        c: 1,
        d: 2,
    };
    assert_eq!(expected, de.unwrap()) //success
}
```

**Comment by Mingun** [comment]
That is problem with serde `flatten` feature, that is not well-designed. Unfortunately, we cannot do anything at quick-xml side. The fix of serde-rs/serde#1183 is required.

**Comment by meettitan** [comment]
@Mingun, Do you have a suggested workaround for factoring out multiple redundant keys? Maybe a macro that defines my structs and inherits all redundant keys?

**Comment by Mingun** [comment]
No, I have no ready-to-use recipes. A custom macro that defines actual struct and it's serialized representation is the best choice for the moment
