### ISSUE TITLE
Is there a recommended way to obtain the line number to a buffer position?

### ISSUE THREAD

**Issue by pacman82** [tafia/quick-xml#72]
I would like to know the line in which an error occurred. Is there already a way of doing this?

**Comment by tafia** [comment]
No unfortunately quick-xml does not search for new lines. The only this is provides is the `buffer_position` which is just the number of bytes read (this is up to you to convert it to a particular line).

**Comment by pacman82** [comment]
Thank you for your answer. I think I'll go with implementing my own `Read` on top of the existing one before passing it to quick-xml
