### ISSUE TITLE
About reading output

### ISSUE THREAD

**Issue by xiaocijun** [tafia/quick-xml#724]
Why does the output need to contain ""? Wouldn't it be easier to directly output what was read?

**Comment by Mingun** [comment]
Please explain your issue better. What output? What you mean under "contain an empty string"? Every string by definition contains the empty string.

**Comment by xiaocijun** [comment]
> Please explain your issue better. What output? What you mean under "contain an empty string"? Every string by definition contains the empty string.

I'm sorry. I just learned rust. I run the following code, and its output uses {:? }

https://github.com/tafia/quick-xml/blob/master/examples/read_texts.rs
