### ISSUE TITLE
How to deserialize XML Prolog?

### ISSUE THREAD

**Issue by mmittnacht** [tafia/quick-xml#725]
Let's say I have some xml like this:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<test>Test1</test>
```

How could I create a structure to represent the entire data structure with the prolog?

```rust
#[derive(Debug, Deserialize)]
pub struct Data {
    pub xml_prolog: XmlProlog,
    pub test: String
}

#[derive(Debug, Deserialize)]
pub struct XmlProlog {
    pub version: XmlProlog,
    pub encoding: String,
    pub standalone: String
}
```

Thanks for any help!

**Comment by Mingun** [comment]
[XML Prolog](https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-prolog) (according to the specification, that's all before the root element) is not considered as XML content, so it is not mapped to serde model which works only with document content.

So it is impossible to use serde to read XML declaration as you want. You should create a [`Reader`](https://docs.rs/quick-xml/latest/quick_xml/reader/struct.Reader.html), read the first event and if it is [`Event::Decl`](https://docs.rs/quick-xml/latest/quick_xml/events/enum.Event.html#variant.Decl), process it (maybe you would need to skip `Event::Comment` and `Event::Text` events, although in well-formed XML documents nothing can precede the XML declaration, so if you interested only on strictly well-formed documents, expect only `Event::Decl`).

Unfortunately, it is not possible to get access to the internal reader of existing Deserializer or to create a Deserializer from existing Reader, so some work for parsing will be done twice. We are interested in improvements in that area.

**Comment by mmittnacht** [comment]
Hey @Mingun 

Thank you for taking time to help me with a well detailed response. In our use-case the double serialization might be sufficient enough, though I will think if I can come up with a better approach later on. Thank you very much!
