### ISSUE TITLE
Enhance Error Handling to Include Location Information

### ISSUE THREAD

**Issue by louiseyousre200** [tafia/quick-xml#728]
Hello,

While experimenting with quick_xml, I considered integrating it with ariadne to improve error handling. However, during this process, I encountered limitations in the error reporting functionality. Specifically, when dealing with quick_xml::Error::EndEventMismatch, I found that the error message only includes information about what is "found" and what is "expected".

To enhance error reporting and provide more informative messages, it would be beneficial to include location information for the "found" element. This additional detail would enable developers to present clearer and more user-friendly error messages.

Thank you for considering this enhancement.

Feel free to adjust the title or details as needed!

**Comment by Mingun** [comment]
Yes, this is a known problem that is already tracked in #313 (it is not only about serde), so I close this as duplicate.
