### ISSUE TITLE
Is it faster than html5ever/xml5ever?

### ISSUE THREAD

**Issue by danger89** [tafia/quick-xml#73]
Basically 2 questions:

- Could I use quick-XML to also parse HTML?
- And, if so, is html5ever from servo slower or faster?  https://github.com/servo/html5ever

Kind regards,
Melroy van den Berg

**Comment by tafia** [comment]
Yes you can parse HTML files, and I believe you'll find quick-xml to be much faster.
On the other hand it doesn't check if the HTML is valid (no check on tag names etc...).

**Comment by danger89** [comment]
U sure? Since HTML is not the same as XHTML, like `<br/>` is valid HTML but invalid XML...

**Comment by tafia** [comment]
> `<br/>` is valid HTML but invalid XML

Well it is a valid XML event too (`Empty`). `<br>` on the other hand, while being a valid event per se will never be closed, which can be problematic if you want to validate your xml => **you can decide not to [validate the xml end names](https://docs.rs/quick-xml/0.8.0/quick_xml/reader/struct.Reader.html#method.check_end_names)**.

i believe the html file should parse without an error, but you won't get any meaning of what `<br/>`, `<head>` etc ... mean: they will just be regular events (`Empty(br)`, `Start(head)` ...) for you to manage.

**Comment by danger89** [comment]
You can use the `<!DOCTYPE html>` to determ this kind of behavior. Which is equal to HTML content. Or ` <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"` which means it's XHTML content.

**Comment by danger89** [comment]
Parsing Google.com data:

html5ever: 0.001174961 Seconds
quick-xml: 0.000000829 Seconds

Although I didn't check if the output is really valid/useful of quick-xml.

**Comment by tafia** [comment]
> Do you want to be able to use your project for HTML parsing or only XML like now?..

No I think I would prefer this repo not to know about html in particular. 
I would prefer another html oriented crate if necessary (like actually what html5ever/xml5ever did).

I am afraid there is no formal lexer unfortunately.

> But it is 1417x faster... 👍

I was expecting much faster, but not by this margin!

**Comment by jonas-schievink** [comment]
Building the rcdom is probably taking most of that time, so I wouldn't call this a fair benchmark

**Comment by danger89** [comment]
Correct. Creating a DOM with quick-xml failed so fair:
https://github.com/tafia/quick-xml/pull/56#issuecomment-310488378

**Comment by Ygg01** [comment]
@danger89 
> Could I use quick-XML to also parse HTML?

In theory yes. However in theory you [CAN use regex to parse HTML](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454).

Problem is, there are many "error handling" and "tree insertion" rules that complicate the matter.

**Comment by tafia** [comment]
Closing this, thank you @Ygg01 for your answer.
