### ISSUE TITLE
Is it possible to not Serialize a None element?

### ISSUE THREAD

**Issue by kitplummer** [tafia/quick-xml#742]
Here's what's happening:

```
AN: AnyName { optional: None }
XML: <?xml ?><AnyName><optional/></AnyName>
```

What I want is:

```
AN: AnyName { optional: None }
XML: <?xml ?><AnyName></AnyName>
```

Do I need to manage this myself, or is it possible in the Serializer?

**Comment by adamreichold** [comment]
Did you try [`skip_serializing_if`](https://serde.rs/field-attrs.html#skip_serializing_if) with `Option::is_none`?

**Comment by kitplummer** [comment]
I knew I'd read that somewhere, but for the life of me kept scanning over the `Option::is_none` part.  Thanks much @adamreichold !
