### ISSUE TITLE
Is there a way to know if the XML is different from my Rust structs?

### ISSUE THREAD

**Issue by frederikhors** [tafia/quick-xml#746]
I have this XML:

```xml
<Player>
    <Team>
        <Name>TeamName</Name>
    </Team>
</Player>
```

and I'm using this code to deserialize:

```rust
use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct Player {
    pub Team: Team,
    pub Coach: Coach,
}

#[derive(Debug, Deserialize)]
pub struct Team {
    pub Name: String,
}

impl Player {
    pub fn from_xml(xml: String) -> Result<Player> {
        Ok(quick_xml::de::from_str(&xml)?)
    }
}
```

Everything works perfect. Thanks for your amazing work!

Now I have this need: I would like to know if the XML I'm parsing contains other structs that I don't collect.

Example: if the XML is this instead:

```xml
<Player>
    <Team>
        <Name>TeamName</Name>
    </Team>

    <Coach>
        <Name>CoachName</Name>
    </Coach>
</Player>
```

`Coach` is not in my `Player` Rust struct.

Is there a way to stop the parsing and return an error?

**Comment by Mingun** [comment]
Serde's attribute [`#[serde(deny_unknown_fields)]`](https://serde.rs/container-attrs.html#deny_unknown_fields) should help.
