### ISSUE TITLE
duplicate field `@type` when both default and xsi namespace attribute are present 

### ISSUE THREAD

**Issue by KarstenB** [tafia/quick-xml#757]
The following code fails with `called `Result::unwrap()` on an `Err` value: Custom("duplicate field `@type`")`: 
```rust
use quick_xml::de::from_str;
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize, PartialEq, Debug)]
pub struct MyType {
    pub sub: Sub,
}

#[derive(Deserialize, Serialize, PartialEq, Debug)]
pub struct Sub {
    #[serde(rename = "@type")]
    // also doesn't work, but for a different reason:
    // Custom("missing field `@xsi:type`")
    //#[serde(rename="@xsi:type")]
    pub my_type: String,
}

fn main() {
    let xml=r#"
    <?xml version="1.0"?>
    <bla xmlns="http://myns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <sub type="a" xsi:type="b"/>
    </bla>"#;
    let object: MyType = from_str(&xml).unwrap();
}
```

I am not quite sure if this is a duplicate of #347, but wanted to contribute another piece of test code. Right now I do a stupid string replacement of `xsi:type` with `xsi_type` and quick-xml is still 10 times faster than some of there other crates I tried!

**Comment by Mingun** [comment]
Yes, namespace prefixes does not considered as part of field name because there can be different prefixes for the one namespace even in the same document. This problem is just one consequence of #218, so I close it as duplicate.
