### ISSUE TITLE
how to merge two xml file.

### ISSUE THREAD

**Issue by yujack008** [tafia/quick-xml#768]
is any demo to merge two xml file?

**Comment by Mingun** [comment]
It is unclear what you mean under "merge" and the answer will be different based on this. If you just need to insert piece of one document into another, then create two readers and a `Writer` and `write_event`s from both readers in desired order. The basic example of writing events from one reader in the Readme of this library.

If under the "merge" you mean some sort of what TortoiseGitMerge does, then this is more broad question which is weakly related to XML processing library and more in area of diff and merge algorithms. In general, such algorithms works with tokens and in case of XML `quick_xml::events::Event` can be such token, but then you will not be able to merge attributes inside element.
