### ISSUE TITLE
Text events are not emitted when text node ends exactly at BufferedReader buffer border

### ISSUE THREAD

**Issue by randomdude999** [tafia/quick-xml#774]
Perhaps the title isn't quite clear here. As a concrete example, the document written by this python script:

```py
open('test.xml', 'w').write('<asdf>' + 'a' * (8192 - 6) + '</asdf>')
```

(i.e., a document with a single tag, whose contents end at offset 8192) will cause quick-xml to emit only a Start and End event, with no Text event in the middle. This can be verified with the following rust program, which simply dumps all received events to stderr:

```rs
use quick_xml::events::Event;
use quick_xml::reader::Reader;

fn main() {
    let mut reader = Reader::from_file("test.xml").unwrap();
    let mut buf = Vec::new();
    loop {
        let ev = reader.read_event_into(&mut buf);
        if matches!(ev, Ok(Event::Eof)) { break; }
        dbg!(&ev);
    }
}
```

This prints:

```
[src/main.rs:10:9] &ev = Ok(
    Start(
        BytesStart { buf: Borrowed("asdf"), name_len: 4 },
    ),
)
[src/main.rs:10:9] &ev = Ok(
    End(
        BytesEnd { name: Borrowed("asdf") },
    ),
)
```

---

The root cause seems to be [in the `read_text` of `buffered_reader.rs`](https://github.com/tafia/quick-xml/blob/80f0e7cc4cc3dedf416b9f4f4efd35d89b67cd8c/src/reader/buffered_reader.rs#L53). In this case, reading the text data requires two loop iterations. On the first iteration, `<` is not found in the data, so the entire data is pushed onto `buf` and the loop continues. On the second iteration, `<` is found at position 0, which triggers the special case in the code that returns `ReadTextResult::Markup` instead of `ReadTextResult::UpToMarkup`, and does not indicate that text data was also present.

I think the right fix here would be to only check the zero-position case on the first iteration of the loop.

**Comment by Mingun** [comment]
I just released [0.35.0](https://github.com/tafia/quick-xml/releases/tag/v0.35.0) with this fix.
