### ISSUE TITLE
How to capture additional (unknown) nodes?

### ISSUE THREAD

**Issue by firewave-remo** [tafia/quick-xml#789]
I do have an XML where i am only interested in certain nodes and attributes, but I do need the other nodes and attributes of the XML to serialize them again later. I don't know what these nodes are called and what attributes they have and if they have additional subnodes.

Example

```rust
#[derive(Debug, Deserialize, Serialize)]
struct A {
    #[serde(rename = "@B")]
    b: B,
    #[serde(flatten)]
    other: ???, // How to capture additional elements with their attributes?
}

#[derive(Debug, Deserialize, Serialize)]
struct B {
    #[serde(rename = "@battribute")]
    attribute: String,
    #[serde(flatten)]
    other: Map<String, String>, // any additional attributes
}

...

let xml = r#"
    <?xml version="1.0" encoding="utf-8"?>
    <A>
        <B battribute="..." />
        <C cattribite1="..." cattribute2="">
            <D dattribute1="..." </D>
        </C>
    </A>"#;
```

I was able to capture additional attribute with

```rust
#[serde(flatten)]
other: Map<String, String>, // any additional attributes
```

But i don't know how to achieve this with full nodes. So i am looking for a serde_json::Value equivalent to perform what is described in the serde docs https://serde.rs/attr-flatten.html#capture-additional-fields

Thx for help

**Comment by Mingun** [comment]
Looks like duplicate of #383

**Comment by firewave-remo** [comment]
Yeah looks like it. Sorry I went through dozens of Issues but was not able to find this one. Hope there will be a solution in the future.
