### ISSUE TITLE
get_encoding method for Reader

### ISSUE THREAD

**Issue by pacman82** [tafia/quick-xml#79]
Would you be open to the idea of exposing the encoding used by `Reader` via a `get_encoding` method?

* In my use case I'm interested in more than the `decode` method (i.e. the name of the encoding).
* Sometimes I pass the a `&Reader` into a function, only so it can call decode. Being able to pass an `&Encoding` would express my intent clearer and help me get rid of generic parameter introduced by `Reader` further reducing some noise.

Usually I am all against to many getter functions, since they are a sign of a leaky abstraction. Yet, I am using `quick-xml` precisely because it is not an abstraction, but does allow my to make many low level decisions.

That being said, I do have a workaround. So if you this collides with your design, I would not mind too much.

**Comment by tafia** [comment]
I am totally open to the idea. I haven't done it yet mostly because I didn't need it and I didn't think someone would.
