### ISSUE TITLE
Confusing error: "missing field `$value`"

### ISSUE THREAD

**Issue by zaczkows** [tafia/quick-xml#790]
First of all thank you for your hard work and excellent crate :smile: 

I'm currently trying to finalize xml init file reader in our project and looking into error messages, so users know what is wrong and can quickly identify issues. However, as other cases looks ok, one is killing the experience: `$value`. When used e.g. in a struct's field, when missing in xml it returns confusing error: "missing field `$value`". This could be mapped to the specific field when existing only in one place, but in more complex scenarios, exactly the same error description will be used for multiple missing items.

Example:
```rust
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AuthorizationMethod {
    Basic { user: String, password: String },
    Mtls { identity: String },
}

#[derive(Deserialize)]
pub struct Authorization {
    #[serde(rename = "$value")]
    pub method: AuthorizationMethod,
}

#[derive(Deserialize)]
pub struct TheXml {
    pub authorization: Authorization,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn correct_parsing() {
        let data = r#"
<xml>
<authorization>
<basic><user>hello</user><password>world</password></basic>
</authorization>
</xml>
"#;
        let result = quick_xml::de::from_str::<TheXml>(&data);
        assert!(result.is_ok());
    }

    #[test]
    fn confusing_error_code() {
        let data = r#"
<xml>
<authorization>
</authorization>
</xml>
"#;
        let result = quick_xml::de::from_str::<TheXml>(&data);
        assert!(result.is_err());
        assert_eq!(result.err().unwrap().to_string(), "missing field `$value`");
    }
}
```

**Comment by Mingun** [comment]
I'm afraid, that quick_xml cannot improve error here, because it is generated by serde machinery, but I'm open to suggestions what can be improved.

I think, it will be easier to influence the error from the type side, for example, using `#[serde(expecting = "...")]`.

Because it is unlikely, that we can improve situation from quick_xml side, I close the issue, but you are free to investigate possible solutions and post them here.
