### ISSUE TITLE
Custom XML serialize/deserialize derive macro

### ISSUE THREAD

**Issue by FlixCoder** [tafia/quick-xml#818]
Hi! First of all, thank you for the work and the library!

I am encountering the expected issues that arise when using serde with quick-xml:

- For example #226 and all duplicates leading to https://github.com/serde-rs/serde/issues/1183 => unability to use `serde(flatten)`
- Lack of XML namespaces support

The actual fix seems to be not to use serde. However, manually deserializing all the structs with quick-xml `NsReader` is quite a bit of effort. The idea would be to provide some kind of derive macro for this that supports more use cases for XML.

This is probably out of scope for this library right? Is there any known effort or recommendations for this? `yaserde` was a library that previously did this, but it is outdated and unmaintained.

Thanks!

**Comment by Mingun** [comment]
Yes, that library already exist and it is based on quick-xml! [xmlserde](https://lib.rs/crates/xmlserde).
