### ISSUE TITLE
(De)serializing `xsi` attributes (`xsi:type`, `xsi:nil` etc.)

### ISSUE THREAD

**Issue by furtidev** [tafia/quick-xml#822]
I'm currently working the following XML:
```xml
<items>
    <Item xsi:type="Weapon">...</Item>
    <Item xsi:nil="true" />
   <Item xsi:type="Shovel">...</Item>
    <Item xsi:nil="true" />
    <Item xsi:nil="true" />
    <Item xsi:nil="true" />
   <Item xsi:type="Food">...</Item>
</items>
```
Here's my struct (note that I'm only trying to handle the `xsi` attributes here for simplicity's sake):
```rust
#[derive(Debug, Deserialize, Serialize, PartialEq)]
#[allow(non_snake_case)]
pub struct Item {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "@type")]
    pub xsi_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "@nil")]
    pub xsi_nil: Option<bool>,
}
```
While this does deserialize the attributes (also, `@xsi:type` and `@xsi_nil` doesn't work), serialization doesn't work as expected. The serializer output looks something like this:
```xml
<items>
    <Item type="Weapon">...</Item>
    <Item nil="true" />
   <Item type="Shovel">...</Item>
    <Item nil="true" />
    <Item nil="true" />
    <Item nil="true" />
   <Item type="Food">...</Item>
</items>
```
But I need these to be `xsi` attributes. So I'm curious how this could be done accurately. Or perhaps it's not possible?

**Comment by furtidev** [comment]
Found a workaround here: https://github.com/tafia/quick-xml/issues/553#issuecomment-1432966843
I really think should be in the docs.

**Comment by Mingun** [comment]
I think, this is one of cases that tracked in #218, so I close this as duplicate
