### ISSUE TITLE
How to deserialize text with Unit inside and save position of Unit within text?

### ISSUE THREAD

**Issue by squeaktoy** [tafia/quick-xml#829]
I have the following XML:
```xml
<stream-uri>http://localhost:8889/<name />/</stream-uri>
```
and I want to deserialize this into a Rust struct with quick-xml's serde integration. Now how would I also save the position that `<name />` finds itself in?

**Comment by Mingun** [comment]
Currently you cannot get the position from the deserializer. The good solution would be to integrate with [serde_spanned](https://lib.rs/crates/serde_spanned), but someone needs to write that integration and corresponding tests. The corresponding feature is tracked is #695 so I close this as duplicate.
