### ISSUE TITLE
self-closing xml tags

### ISSUE THREAD

**Issue by amandahugandkiss** [tafia/quick-xml#835]
Is there a mechanism within quick-xml to capture elements (events) which are self-closing:

`<Element DateUpdated="2022-11-19" DateCreated="2022-11-13"/>`

I vaguely recall seeing notation that a start and end tag is required but cannot locate it at the moment and did scan the issues list unsucessfully.

Thank you.

**Comment by Mingun** [comment]
Yes, of course. I assume that you enabled [expand_empty_elements](https://docs.rs/quick-xml/latest/quick_xml/reader/struct.Config.html#structfield.expand_empty_elements) configuration option of a `Reader` which converts all `Empty` events to `Start` and `End` events.

**Comment by amandahugandkiss** [comment]
Much appreciated -- clearly missed that detail.  Thank you
