### ISSUE TITLE
streaming bzip/gzip support

### ISSUE THREAD

**Issue by cakey** [tafia/quick-xml#86]
Hey!

Thanks for providing this library!

I was wondering if there could be big performance wins from reduced io by supporting streaming from gzip/bzip.

I was wondering how easy it would be to plug this in, or what benefits we might see. I'm happy to lead the work if you had any ideas about where I might start?

Thanks
Ben

**Comment by tafia** [comment]
I think this probably shouldn't be implemented directly in quick-xml. It is better to let people choose their deflate crate and their encoding method.

For instance, it should be easy enough to wrap this kind of reader: https://docs.rs/inflate/0.3.0/inflate/struct.DeflateDecoder.html into a `BufReader` and use it directly with quick-xml. I'm not certain you can get more performance win than that.

Let me know if I'm not clear.

**Comment by tafia** [comment]
@cakey , can I close it or there is something I didn't see?

**Comment by cakey** [comment]
Ah, you're absolutely right, I missed there was a from_reader constructor.

Thank you! Good to close :)
